"""Comprehensive edge-case, failure-mode, and R-concordance tests.

Organized into:
  1. ComBat R concordance — varied scenarios (large, unbalanced, minimal, etc.)
  2. limma R concordance — varied scenarios
  3. HarmonizR pipeline R concordance — including missing-data scenarios
  4. ComBat failure modes and edge cases
  5. limma failure modes and edge cases
  6. Pipeline failure modes and edge cases
  7. Numerical stability and determinism
  8. spotting / splitting unit tests

All R reference values generated by generate_edgecase_fixtures.R.
"""

import numpy as np
import pandas as pd
import pytest
from pathlib import Path

from harmonizepy.combat import combat
from harmonizepy.combat_wrapper import adjust_combat
from harmonizepy.limma_wrapper import remove_batch_effect, adjust_limma
from harmonizepy.core import harmonize
from harmonizepy.spotting import spotting_missing_values
from harmonizepy.splitting import splitting
from harmonizepy.rebuild import rebuild

# ---------------------------------------------------------------------------
# Fixture helpers
# ---------------------------------------------------------------------------

FIXTURE_DIR = Path(__file__).parent / "fixtures"


def _load_tsv(name: str) -> np.ndarray:
    df = pd.read_csv(FIXTURE_DIR / name, sep="\t", index_col=0)
    return df.values


def _load_tsv_df(name: str) -> pd.DataFrame:
    return pd.read_csv(FIXTURE_DIR / name, sep="\t", index_col=0)


def _load_batch(name: str) -> np.ndarray:
    return pd.read_csv(FIXTURE_DIR / name)["batch"].values


def _fixture_exists(name: str) -> bool:
    return (FIXTURE_DIR / name).exists()


# ===================================================================
# 1. ComBat vs R sva::ComBat — extended scenarios
# ===================================================================

_DATASETS = {
    "large": {
        "input": "large_input.tsv", "batch": "large_batch.csv",
        "modes": [1, 2, 3, 4], "fixture": "large_combat_mode{}.tsv",
    },
    "unbalanced": {
        "input": "unbalanced_input.tsv", "batch": "unbalanced_batch.csv",
        "modes": [1, 2, 3, 4], "fixture": "unbalanced_combat_mode{}.tsv",
    },
    "minimal": {
        "input": "minimal_input.tsv", "batch": "minimal_batch.csv",
        # mode 1 fails in R too (2 features, convergence error), skip it
        # mode 4 is identical to mode 2 for this tiny dataset
        "modes": [2, 3], "fixture": "minimal_combat_mode{}.tsv",
    },
    "highvar": {
        "input": "highvar_input.tsv", "batch": "highvar_batch.csv",
        "modes": [1, 2, 3, 4], "fixture": "highvar_combat_mode{}.tsv",
    },
    "nearconstant": {
        "input": "nearconstant_input.tsv", "batch": "nearconstant_batch.csv",
        # Only mean_only modes (2, 4) for near-constant features
        "modes": [2, 4], "fixture": "nearconstant_combat_mode{}.tsv",
    },
    "negative": {
        "input": "negative_input.tsv", "batch": "negative_batch.csv",
        "modes": [1, 2, 3, 4], "fixture": "negative_combat_mode{}.tsv",
    },
    "wide": {
        "input": "wide_input.tsv", "batch": "wide_batch.csv",
        "modes": [1, 2, 3, 4], "fixture": "wide_combat_mode{}.tsv",
    },
}

_MODE_PARAMS = {
    1: {"par_prior": True, "mean_only": False},
    2: {"par_prior": True, "mean_only": True},
    3: {"par_prior": False, "mean_only": False},
    4: {"par_prior": False, "mean_only": True},
}


def _combat_test_cases():
    """Yield (dataset_name, mode) tuples for parametrize."""
    for name, spec in _DATASETS.items():
        for mode in spec["modes"]:
            fixture = spec["fixture"].format(mode)
            if _fixture_exists(fixture):
                yield pytest.param(name, mode, id=f"{name}-mode{mode}")


@pytest.mark.skipif(
    not _fixture_exists("large_combat_mode1.tsv"),
    reason="Edge-case R fixtures not generated",
)
class TestCombatRConcordanceExtended:
    """ComBat output must match R sva::ComBat across diverse scenarios."""

    @pytest.mark.parametrize("dataset,mode", list(_combat_test_cases()))
    def test_vs_r_sva(self, dataset, mode):
        spec = _DATASETS[dataset]
        data = _load_tsv(spec["input"])
        batch = _load_batch(spec["batch"])
        expected = _load_tsv(spec["fixture"].format(mode))
        params = _MODE_PARAMS[mode]

        result = combat(data, batch, **params)

        # Mode 1 (parametric iterative) has slightly higher tolerance
        rtol = 1e-4 if mode == 1 else 1e-6
        atol = 1e-5 if mode == 1 else 1e-8
        # Nonparametric modes on large data can have slightly more divergence
        if mode == 3 and dataset == "large":
            rtol = 5e-4
            atol = 1e-4

        # R produces NaN for near-constant features (pooled var ≈ 0);
        # our implementation clamps var_pooled > 0 and returns numbers.
        # Compare only where R produced non-NaN, then verify R-NaN rows
        # are from near-constant features (low within-batch variance).
        r_nan_mask = np.isnan(expected)
        if r_nan_mask.any():
            # Rows where R says NaN — verify they have near-zero residual var
            nan_rows = np.where(r_nan_mask.any(axis=1))[0]
            unique_b = np.unique(batch)
            for r in nan_rows:
                # Check within-batch variance (what R actually uses for pooled var)
                within_vars = [data[r, batch == b].var(ddof=1)
                               for b in unique_b if (batch == b).sum() > 1]
                max_within_var = max(within_vars) if within_vars else 0
                assert max_within_var < 0.1, (
                    f"R output NaN for row {r} but max within-batch "
                    f"var={max_within_var:.2e}"
                )
            # Compare non-NaN portion
            valid = ~r_nan_mask
            if valid.any():
                np.testing.assert_allclose(
                    result[valid], expected[valid], rtol=rtol, atol=atol,
                    err_msg=f"{dataset} mode {mode}: mismatch vs R sva::ComBat",
                )
        else:
            np.testing.assert_allclose(
                result, expected, rtol=rtol, atol=atol,
                err_msg=f"{dataset} mode {mode}: mismatch vs R sva::ComBat",
            )

    @pytest.mark.parametrize("dataset,mode", list(_combat_test_cases()))
    def test_shape_preserved(self, dataset, mode):
        spec = _DATASETS[dataset]
        data = _load_tsv(spec["input"])
        batch = _load_batch(spec["batch"])
        result = combat(data, batch, **_MODE_PARAMS[mode])
        assert result.shape == data.shape

    @pytest.mark.parametrize("dataset,mode", list(_combat_test_cases()))
    def test_no_nan_in_output(self, dataset, mode):
        spec = _DATASETS[dataset]
        data = _load_tsv(spec["input"])
        batch = _load_batch(spec["batch"])
        result = combat(data, batch, **_MODE_PARAMS[mode])
        assert not np.isnan(result).any(), f"NaN in {dataset} mode {mode}"

    @pytest.mark.parametrize("dataset,mode", list(_combat_test_cases()))
    def test_batch_means_converge(self, dataset, mode):
        """After correction, batch means should be more similar."""
        spec = _DATASETS[dataset]
        data = _load_tsv(spec["input"])
        batch = _load_batch(spec["batch"])
        result = combat(data, batch, **_MODE_PARAMS[mode])

        unique_b = np.unique(batch)
        means_before = [data[:, batch == b].mean() for b in unique_b]
        means_after = [result[:, batch == b].mean() for b in unique_b]
        spread_before = max(means_before) - min(means_before)
        spread_after = max(means_after) - min(means_after)
        assert spread_after < spread_before + 1e-10, (
            f"{dataset} mode {mode}: spread not reduced "
            f"{spread_before:.4f} → {spread_after:.4f}"
        )


# ===================================================================
# 2. limma vs R limma::removeBatchEffect — extended scenarios
# ===================================================================

_LIMMA_DATASETS = {
    "large": {"input": "large_input.tsv", "batch": "large_batch.csv",
              "fixture": "large_limma.tsv"},
    "unbalanced": {"input": "unbalanced_input.tsv", "batch": "unbalanced_batch.csv",
                   "fixture": "unbalanced_limma.tsv"},
    "minimal": {"input": "minimal_input.tsv", "batch": "minimal_batch.csv",
                "fixture": "minimal_limma.tsv"},
    "highvar": {"input": "highvar_input.tsv", "batch": "highvar_batch.csv",
                "fixture": "highvar_limma.tsv"},
    "nearconstant": {"input": "nearconstant_input.tsv",
                     "batch": "nearconstant_batch.csv",
                     "fixture": "nearconstant_limma.tsv"},
    "negative": {"input": "negative_input.tsv", "batch": "negative_batch.csv",
                 "fixture": "negative_limma.tsv"},
    "wide": {"input": "wide_input.tsv", "batch": "wide_batch.csv",
             "fixture": "wide_limma.tsv"},
}


def _limma_test_cases():
    for name, spec in _LIMMA_DATASETS.items():
        if _fixture_exists(spec["fixture"]):
            yield pytest.param(name, id=name)


@pytest.mark.skipif(
    not _fixture_exists("large_limma.tsv"),
    reason="Edge-case R fixtures not generated",
)
class TestLimmaRConcordanceExtended:
    """limma output must match R limma::removeBatchEffect."""

    @pytest.mark.parametrize("dataset", list(_limma_test_cases()))
    def test_vs_r_limma(self, dataset):
        spec = _LIMMA_DATASETS[dataset]
        data = _load_tsv(spec["input"])
        batch = _load_batch(spec["batch"])
        expected = _load_tsv(spec["fixture"])
        result = remove_batch_effect(data, batch)

        np.testing.assert_allclose(
            result, expected, rtol=1e-10, atol=1e-10,
            err_msg=f"{dataset}: mismatch vs R limma",
        )

    @pytest.mark.parametrize("dataset", list(_limma_test_cases()))
    def test_shape_no_nan(self, dataset):
        spec = _LIMMA_DATASETS[dataset]
        data = _load_tsv(spec["input"])
        batch = _load_batch(spec["batch"])
        result = remove_batch_effect(data, batch)
        assert result.shape == data.shape
        assert not np.isnan(result).any()


# ===================================================================
# 3. HarmonizR pipeline R concordance — large + sparse + medium limma
# ===================================================================

@pytest.mark.skipif(
    not _fixture_exists("large_combat_mode1.tsv"),
    reason="Large R fixtures not generated",
)
class TestHarmonizRLargeConcordance:
    """Full pipeline vs R sva::ComBat for large (no-missing) dataset."""

    @pytest.fixture(autouse=True)
    def _load(self):
        self.data = _load_tsv_df("large_input.tsv")
        batch_csv = pd.read_csv(FIXTURE_DIR / "large_batch.csv")
        self.desc = batch_csv

    @pytest.mark.parametrize("mode", [1, 2, 3, 4])
    def test_combat_modes(self, mode):
        expected = _load_tsv("large_combat_mode{}.tsv".format(mode))
        result = harmonize(
            self.data, self.desc,
            algorithm="ComBat", combat_mode=mode,
        )
        rtol = 1e-4 if mode in (1, 3) else 1e-6
        atol = 1e-5 if mode in (1, 3) else 1e-8
        # Large nonparametric needs a bit more tolerance
        if mode == 3:
            rtol = 5e-4
            atol = 1e-4
        np.testing.assert_allclose(
            result.values, expected, rtol=rtol, atol=atol,
            err_msg=f"Large HarmonizR ComBat mode {mode}",
        )


@pytest.mark.skipif(
    not _fixture_exists("sparse_harmonizr_combat_mode1.tsv"),
    reason="Sparse HarmonizR fixtures not generated",
)
class TestHarmonizRSparseConcordance:
    """Full pipeline vs R HarmonizR for sparse (50% batches missing)."""

    @pytest.fixture(autouse=True)
    def _load(self):
        self.data = _load_tsv_df("sparse_input.tsv")
        batch_csv = pd.read_csv(FIXTURE_DIR / "sparse_batch.csv")
        self.desc = batch_csv

    @pytest.mark.parametrize("mode", [1, 2, 3, 4])
    def test_combat_modes(self, mode):
        expected_df = _load_tsv_df(
            "sparse_harmonizr_combat_mode{}.tsv".format(mode)
        )
        result = harmonize(
            self.data, self.desc,
            algorithm="ComBat", combat_mode=mode,
        )
        # Align by shared features (index) and columns
        shared_idx = result.index.intersection(expected_df.index)
        shared_cols = result.columns.intersection(expected_df.columns)
        r = result.loc[shared_idx, shared_cols].values
        e = expected_df.loc[shared_idx, shared_cols].values

        # Both have NaN in the same places
        nan_mask = np.isnan(e)
        assert np.isnan(r[nan_mask]).all(), "Expected NaN where R has NaN"

        # Compare non-NaN values
        valid = ~nan_mask
        if valid.any():
            rtol = 5e-4 if mode in (1, 3) else 1e-5
            np.testing.assert_allclose(
                r[valid], e[valid], rtol=rtol, atol=1e-4,
                err_msg=f"Sparse HarmonizR ComBat mode {mode}",
            )


@pytest.mark.skipif(
    not _fixture_exists("medium_harmonizr_limma.tsv"),
    reason="Medium HarmonizR limma fixture not generated",
)
class TestHarmonizRMediumLimma:
    """Pipeline vs R HarmonizR for medium dataset with limma."""

    def test_limma(self):
        data = _load_tsv_df("medium_input.tsv")
        batch_csv = pd.read_csv(FIXTURE_DIR / "medium_batch.csv")
        expected_df = _load_tsv_df("medium_harmonizr_limma.tsv")
        result = harmonize(data, batch_csv, algorithm="limma")

        shared_idx = result.index.intersection(expected_df.index)
        shared_cols = result.columns.intersection(expected_df.columns)
        r = result.loc[shared_idx, shared_cols].values
        e = expected_df.loc[shared_idx, shared_cols].values

        nan_mask = np.isnan(e)
        assert np.isnan(r[nan_mask]).all(), "Expected NaN where R has NaN"

        valid = ~nan_mask
        if valid.any():
            np.testing.assert_allclose(
                r[valid], e[valid], rtol=1e-8, atol=1e-8,
                err_msg="Medium HarmonizR limma",
            )


# ===================================================================
# 4. ComBat — failure modes and edge cases
# ===================================================================

class TestCombatFailureModes:
    """Verify combat raises clear errors on bad input."""

    def test_1d_input_rejected(self):
        with pytest.raises(ValueError, match="2-D"):
            combat(np.array([1.0, 2.0, 3.0]), np.array([0, 0, 1]))

    def test_3d_input_rejected(self):
        with pytest.raises(ValueError, match="2-D"):
            combat(np.zeros((2, 3, 4)), np.array([0, 0, 1]))

    def test_nan_raises(self):
        data = np.array([[1.0, 2.0, 3.0, 4.0], [np.nan, 6.0, 7.0, 8.0]])
        with pytest.raises(ValueError, match="NaN"):
            combat(data, np.array([0, 0, 1, 1]))

    def test_single_feature_rejected(self):
        with pytest.raises(ValueError, match=">= 2"):
            combat(np.array([[1.0, 2.0, 3.0, 4.0]]), np.array([0, 0, 1, 1]))

    def test_batch_length_mismatch(self):
        data = np.random.default_rng(1).normal(size=(5, 6))
        with pytest.raises(ValueError, match="batch length"):
            combat(data, np.array([0, 0, 1]))

    def test_invalid_ref_batch(self):
        data = np.random.default_rng(1).normal(size=(5, 6))
        batch = np.array([0, 0, 0, 1, 1, 1])
        with pytest.raises(ValueError, match="ref_batch"):
            combat(data, batch, ref_batch=99)

    def test_single_batch_returns_copy(self):
        """Single batch → data returned unchanged."""
        data = np.random.default_rng(2).normal(10, 2, size=(10, 4))
        batch = np.array([0, 0, 0, 0])
        result = combat(data, batch)
        np.testing.assert_array_equal(result, data)
        # Must be a copy, not the same object
        assert result is not data

    def test_empty_features_many_samples(self):
        """Two features, many samples — should not crash."""
        rng = np.random.default_rng(3)
        data = rng.normal(10, 1, size=(2, 20))
        data[:, 10:] += 3.0
        batch = np.array([0] * 10 + [1] * 10)
        result = combat(data, batch, par_prior=True, mean_only=True)
        assert result.shape == data.shape
        assert not np.isnan(result).any()


class TestCombatEdgeCaseBehavior:
    """Behavioral edge cases — not errors, but tricky inputs."""

    def test_noncontiguous_labels(self):
        """Labels like [5, 5, 10, 10] work via remapping."""
        rng = np.random.default_rng(10)
        data = rng.normal(10, 2, size=(20, 8))
        data[:, 4:] += 3.0
        batch = np.array([5, 5, 5, 5, 10, 10, 10, 10])
        result = combat(data, batch)
        assert result.shape == data.shape
        assert not np.isnan(result).any()

    def test_string_int_labels(self):
        """Batch labels as strings representing ints should work after conversion."""
        rng = np.random.default_rng(11)
        data = rng.normal(10, 2, size=(10, 6))
        data[:, 3:] += 2.0
        batch = np.array([1, 1, 1, 2, 2, 2])
        result = combat(data, batch)
        assert result.shape == data.shape

    def test_ref_batch_preserves_reference(self):
        """Reference batch data must be exactly unchanged."""
        rng = np.random.default_rng(12)
        data = rng.normal(10, 2, size=(20, 9))
        data[:, 3:6] += 3.0
        data[:, 6:] -= 2.0
        batch = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2])
        for ref_b in [0, 1, 2]:
            result = combat(data, batch, ref_batch=ref_b)
            ref_cols = batch == ref_b
            np.testing.assert_array_equal(
                result[:, ref_cols], data[:, ref_cols],
                err_msg=f"ref_batch={ref_b}: reference data changed",
            )

    def test_ref_batch_with_noncontiguous_labels(self):
        """ref_batch refers to original labels, not remapped ones."""
        rng = np.random.default_rng(13)
        data = rng.normal(10, 2, size=(15, 8))
        data[:, 4:] += 4.0
        batch = np.array([10, 10, 10, 10, 20, 20, 20, 20])
        result = combat(data, batch, ref_batch=10)
        ref_cols = batch == 10
        np.testing.assert_array_equal(result[:, ref_cols], data[:, ref_cols])

    def test_identical_batches_no_change(self):
        """If batches have no real effect, output should ≈ input."""
        rng = np.random.default_rng(14)
        data = rng.normal(10, 1, size=(30, 8))
        batch = np.array([0, 0, 0, 0, 1, 1, 1, 1])
        result = combat(data, batch, par_prior=True, mean_only=True)
        # Should be very close to input since no real batch effect
        np.testing.assert_allclose(result, data, atol=1.0,
                                   err_msg="Large change with no real batch effect")

    def test_all_negative_data(self):
        """Negative data should work fine (e.g., log2FC)."""
        rng = np.random.default_rng(15)
        data = rng.normal(-5, 2, size=(20, 8))
        data[:, 4:] -= 3.0
        batch = np.array([0, 0, 0, 0, 1, 1, 1, 1])
        result = combat(data, batch)
        assert result.shape == data.shape
        assert not np.isnan(result).any()

    def test_very_large_values(self):
        """Data with very large values should not overflow."""
        rng = np.random.default_rng(16)
        data = rng.normal(1e6, 1e4, size=(10, 6))
        data[:, 3:] += 1e5
        batch = np.array([0, 0, 0, 1, 1, 1])
        result = combat(data, batch, par_prior=True, mean_only=True)
        assert not np.isnan(result).any()
        assert np.isfinite(result).all()

    def test_very_small_values(self):
        """Near-zero data should not cause division issues."""
        rng = np.random.default_rng(17)
        data = rng.normal(1e-10, 1e-12, size=(10, 6))
        data[:, 3:] += 1e-10
        batch = np.array([0, 0, 0, 1, 1, 1])
        result = combat(data, batch, par_prior=True, mean_only=True)
        assert not np.isnan(result).any()
        assert np.isfinite(result).all()

    def test_many_batches(self):
        """Works with many batches (10)."""
        rng = np.random.default_rng(18)
        n_batches = 10
        n_per = 3
        data = rng.normal(10, 2, size=(20, n_batches * n_per))
        batch = np.repeat(range(n_batches), n_per)
        for b in range(n_batches):
            data[:, batch == b] += rng.normal(0, 2)
        result = combat(data, batch, par_prior=True, mean_only=True)
        assert result.shape == data.shape
        assert not np.isnan(result).any()

    def test_wrapper_mode_dispatch(self):
        """adjust_combat correctly dispatches all 4 modes."""
        rng = np.random.default_rng(19)
        df = pd.DataFrame(
            rng.normal(10, 2, size=(15, 8)),
            index=[f"p_{i}" for i in range(15)],
            columns=[f"s_{j}" for j in range(8)],
        )
        df.iloc[:, 4:] += 3.0
        batch = np.array([0, 0, 0, 0, 1, 1, 1, 1])
        for mode in [1, 2, 3, 4]:
            result = adjust_combat(df, batch, mode=mode)
            assert isinstance(result, pd.DataFrame)
            assert list(result.index) == list(df.index)
            assert list(result.columns) == list(df.columns)

    def test_wrapper_single_batch_passthrough(self):
        """adjust_combat with single batch returns copy."""
        df = pd.DataFrame(
            np.random.default_rng(20).normal(size=(5, 4)),
            index=[f"p_{i}" for i in range(5)],
            columns=[f"s_{j}" for j in range(4)],
        )
        batch = np.array([1, 1, 1, 1])
        result = adjust_combat(df, batch, mode=1)
        pd.testing.assert_frame_equal(result, df)


# ===================================================================
# 5. limma — failure modes and edge cases
# ===================================================================

class TestLimmaFailureModes:
    def test_1d_rejected(self):
        with pytest.raises(ValueError, match="2-D"):
            remove_batch_effect(np.array([1, 2, 3]), np.array([0, 0, 1]))

    def test_nan_rejected(self):
        data = np.array([[1.0, np.nan], [3.0, 4.0]])
        with pytest.raises(ValueError, match="NaN"):
            remove_batch_effect(data, np.array([0, 1]))

    def test_batch_length_mismatch(self):
        data = np.random.default_rng(1).normal(size=(5, 4))
        with pytest.raises(ValueError, match="batch length"):
            remove_batch_effect(data, np.array([0, 1]))

    def test_single_batch_passthrough(self):
        data = np.random.default_rng(2).normal(size=(5, 4))
        batch = np.array([0, 0, 0, 0])
        result = remove_batch_effect(data, batch)
        np.testing.assert_array_equal(result, data)
        assert result is not data


class TestLimmaEdgeCaseBehavior:
    def test_many_batches(self):
        """limma handles 5 batches."""
        rng = np.random.default_rng(30)
        data = rng.normal(10, 2, size=(20, 15))
        batch = np.repeat(range(5), 3)
        for b in range(5):
            data[:, batch == b] += rng.normal(0, 2)
        result = remove_batch_effect(data, batch)
        assert result.shape == data.shape
        assert not np.isnan(result).any()

    def test_negative_data(self):
        rng = np.random.default_rng(31)
        data = rng.normal(-5, 3, size=(15, 6))
        data[:, 3:] -= 4.0
        batch = np.array([0, 0, 0, 1, 1, 1])
        result = remove_batch_effect(data, batch)
        assert not np.isnan(result).any()

    def test_adjust_limma_preserves_index(self):
        """DataFrame wrapper preserves index and columns."""
        rng = np.random.default_rng(32)
        df = pd.DataFrame(
            rng.normal(10, 2, size=(8, 6)),
            index=[f"gene_{i}" for i in range(8)],
            columns=[f"samp_{j}" for j in range(6)],
        )
        df.iloc[:, 3:] += 2.0
        batch = np.array([0, 0, 0, 1, 1, 1])
        result = adjust_limma(df, batch)
        assert list(result.index) == list(df.index)
        assert list(result.columns) == list(df.columns)

    def test_unbalanced_batches(self):
        """Unbalanced batches (2, 5, 3 samples)."""
        rng = np.random.default_rng(33)
        data = rng.normal(10, 2, size=(20, 10))
        batch = np.array([0, 0, 1, 1, 1, 1, 1, 2, 2, 2])
        data[:, batch == 1] += 2.0
        data[:, batch == 2] -= 1.5
        result = remove_batch_effect(data, batch)
        assert result.shape == data.shape
        assert not np.isnan(result).any()

    def test_large_scale(self):
        """500 features × 30 samples — must not be slow or unstable."""
        rng = np.random.default_rng(34)
        data = rng.normal(10, 2, size=(500, 30))
        batch = np.repeat(range(5), 6)
        for b in range(5):
            data[:, batch == b] += rng.normal(0, 3)
        result = remove_batch_effect(data, batch)
        assert not np.isnan(result).any()
        assert np.isfinite(result).all()

    def test_2_features_2_samples_per_batch(self):
        """Minimal valid limma case."""
        data = np.array([[1.0, 2.0, 5.0, 6.0],
                         [3.0, 4.0, 7.0, 8.0]])
        batch = np.array([0, 0, 1, 1])
        result = remove_batch_effect(data, batch)
        assert result.shape == (2, 4)
        assert not np.isnan(result).any()


# ===================================================================
# 6. Pipeline — failure modes and edge cases
# ===================================================================

class TestPipelineFailureModes:
    def test_mismatched_samples(self):
        """Description has different number of samples than data."""
        data = pd.DataFrame(
            np.random.default_rng(1).normal(size=(5, 4)),
            columns=["s1", "s2", "s3", "s4"],
        )
        desc = pd.DataFrame({
            "ID": ["s1", "s2", "s3"],
            "sample": [1, 2, 3],
            "batch": [1, 1, 2],
        })
        with pytest.raises(ValueError, match="samples"):
            harmonize(data, desc)

    def test_all_missing_feature(self):
        """Feature with all NaN should appear as NaN in output."""
        data = pd.DataFrame(
            np.random.default_rng(2).normal(10, 1, size=(5, 6)),
            index=[f"p_{i}" for i in range(5)],
            columns=[f"s_{j}" for j in range(6)],
        )
        data.iloc[0, :] = np.nan
        desc = pd.DataFrame({
            "ID": data.columns.tolist(),
            "sample": list(range(1, 7)),
            "batch": [1, 1, 1, 2, 2, 2],
        })
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=2)
        assert np.isnan(result.iloc[0]).all(), "All-NaN feature should stay NaN"
        assert not np.isnan(result.iloc[1:]).all(axis=None), "Other features should not be all NaN"

    def test_feature_missing_one_batch_entirely(self):
        """Feature missing one batch -> only adjustable across remaining batches."""
        data = pd.DataFrame(
            np.random.default_rng(3).normal(10, 1, size=(5, 9)),
            index=[f"p_{i}" for i in range(5)],
            columns=[f"s_{j}" for j in range(9)],
        )
        # Make feature 0 missing in batch 3
        data.iloc[0, 6:] = np.nan
        desc = pd.DataFrame({
            "ID": data.columns.tolist(),
            "sample": list(range(1, 10)),
            "batch": [1, 1, 1, 2, 2, 2, 3, 3, 3],
        })
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=2)
        # Feature 0 should have NaN in batch 3 columns
        assert np.isnan(result.iloc[0, 6:]).all()
        # Feature 0 should have values in batches 1-2
        assert not np.isnan(result.iloc[0, :6]).any()

    def test_duplicate_feature_names(self):
        """Duplicate feature indices should be deduplicated."""
        data = pd.DataFrame(
            np.random.default_rng(4).normal(10, 1, size=(4, 6)),
            index=["p_0", "p_0", "p_1", "p_2"],
            columns=[f"s_{j}" for j in range(6)],
        )
        desc = pd.DataFrame({
            "ID": data.columns.tolist(),
            "sample": list(range(1, 7)),
            "batch": [1, 1, 1, 2, 2, 2],
        })
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=2)
        # One of the p_0 duplicates should be dropped
        assert result.shape[0] == 3

    def test_dataframe_input(self):
        """Pipeline accepts DataFrames directly."""
        rng = np.random.default_rng(5)
        data = pd.DataFrame(
            rng.normal(10, 2, size=(10, 6)),
            index=[f"p_{i}" for i in range(10)],
            columns=[f"s_{j}" for j in range(6)],
        )
        data.iloc[:, 3:] += 3.0
        desc = pd.DataFrame({
            "ID": data.columns.tolist(),
            "sample": list(range(1, 7)),
            "batch": [1, 1, 1, 2, 2, 2],
        })
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=2)
        assert isinstance(result, pd.DataFrame)
        assert result.shape == data.shape

    def test_limma_through_pipeline(self):
        """limma algorithm works through the pipeline."""
        rng = np.random.default_rng(6)
        data = pd.DataFrame(
            rng.normal(10, 2, size=(15, 8)),
            index=[f"p_{i}" for i in range(15)],
            columns=[f"s_{j}" for j in range(8)],
        )
        data.iloc[:, 4:] += 3.0
        desc = pd.DataFrame({
            "ID": data.columns.tolist(),
            "sample": list(range(1, 9)),
            "batch": [1, 1, 1, 1, 2, 2, 2, 2],
        })
        result = harmonize(data, desc, algorithm="limma")
        assert isinstance(result, pd.DataFrame)
        assert not np.isnan(result).all(axis=None)


# ===================================================================
# 7. Numerical stability and determinism
# ===================================================================

class TestNumericalStability:
    def test_deterministic_combat(self):
        """Same input always gives same output."""
        rng = np.random.default_rng(50)
        data = rng.normal(10, 2, size=(30, 8))
        data[:, 4:] += 3.0
        batch = np.array([0, 0, 0, 0, 1, 1, 1, 1])

        result1 = combat(data, batch, par_prior=True, mean_only=False)
        result2 = combat(data, batch, par_prior=True, mean_only=False)
        np.testing.assert_array_equal(result1, result2,
                                      err_msg="ComBat not deterministic")

    def test_deterministic_limma(self):
        rng = np.random.default_rng(51)
        data = rng.normal(10, 2, size=(20, 6))
        data[:, 3:] += 2.0
        batch = np.array([0, 0, 0, 1, 1, 1])

        result1 = remove_batch_effect(data, batch)
        result2 = remove_batch_effect(data, batch)
        np.testing.assert_array_equal(result1, result2,
                                      err_msg="limma not deterministic")

    def test_combat_float32_input(self):
        """float32 input should be promoted to float64 without issues."""
        rng = np.random.default_rng(52)
        data = rng.normal(10, 2, size=(20, 6)).astype(np.float32)
        data[:, 3:] += 3.0
        batch = np.array([0, 0, 0, 1, 1, 1])
        result = combat(data, batch)
        assert result.dtype == np.float64
        assert not np.isnan(result).any()

    def test_limma_float32_input(self):
        rng = np.random.default_rng(53)
        data = rng.normal(10, 2, size=(20, 6)).astype(np.float32)
        data[:, 3:] += 2.0
        batch = np.array([0, 0, 0, 1, 1, 1])
        result = remove_batch_effect(data, batch)
        assert result.dtype == np.float64
        assert not np.isnan(result).any()

    def test_combat_output_not_alias(self):
        """Output must not share memory with input."""
        rng = np.random.default_rng(54)
        data = rng.normal(10, 2, size=(10, 6))
        data[:, 3:] += 2.0
        batch = np.array([0, 0, 0, 1, 1, 1])
        original = data.copy()
        result = combat(data, batch)
        # Mutating result should not affect original
        result[0, 0] = -9999.0
        np.testing.assert_array_equal(data, original)

    def test_limma_output_not_alias(self):
        rng = np.random.default_rng(55)
        data = rng.normal(10, 2, size=(10, 6))
        data[:, 3:] += 2.0
        batch = np.array([0, 0, 0, 1, 1, 1])
        original = data.copy()
        result = remove_batch_effect(data, batch)
        result[0, 0] = -9999.0
        np.testing.assert_array_equal(data, original)

    def test_combat_integer_data(self):
        """Integer input should be handled (promoted to float)."""
        data = np.array([[10, 12, 15, 18], [5, 7, 11, 14]], dtype=np.int64)
        batch = np.array([0, 0, 1, 1])
        result = combat(data, batch, par_prior=True, mean_only=True)
        assert result.dtype == np.float64
        assert not np.isnan(result).any()

    def test_combat_uniform_features(self):
        """Features constant within each batch should not blow up."""
        data = np.array([
            [10.0, 10.0, 10.0, 20.0, 20.0, 20.0],
            [5.0, 5.0, 5.0, 15.0, 15.0, 15.0],
            [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
        ])
        batch = np.array([0, 0, 0, 1, 1, 1])
        # mean_only=True should handle this (variance=0 clamped)
        result = combat(data, batch, par_prior=True, mean_only=True)
        assert not np.isnan(result).any()
        assert np.isfinite(result).all()


# ===================================================================
# 8. Spotting logic unit tests
# ===================================================================

class TestSpottingEdgeCases:
    def test_no_missing(self):
        """All data present → every feature sees all batches."""
        data = pd.DataFrame(np.ones((5, 6)))
        batch = np.array([1, 1, 1, 2, 2, 2])
        block = batch.copy()
        result = spotting_missing_values(data, batch, block, needed_values=2)
        assert all(affil == (1, 2) for affil in result)

    def test_one_batch_all_nan(self):
        """Feature entirely NaN in one batch → only other batch in affiliation."""
        data = pd.DataFrame(np.ones((3, 6)))
        data.iloc[0, 3:] = np.nan  # Feature 0: NaN in batch 2
        batch = np.array([1, 1, 1, 2, 2, 2])
        block = batch.copy()
        result = spotting_missing_values(data, batch, block, needed_values=2)
        assert result[0] == (1,)  # Only batch 1 eligible
        assert result[1] == (1, 2)
        assert result[2] == (1, 2)

    def test_feature_insufficient_in_all_batches(self):
        """Feature with < needed_values everywhere → empty affiliation."""
        data = pd.DataFrame(np.ones((3, 6)))
        data.iloc[0, :] = np.nan
        batch = np.array([1, 1, 1, 2, 2, 2])
        block = batch.copy()
        result = spotting_missing_values(data, batch, block, needed_values=2)
        assert result[0] == ()  # No batches qualify

    def test_needed_values_1(self):
        """needed_values=1: only need 1 non-NaN per batch."""
        data = pd.DataFrame(np.ones((3, 6)))
        data.iloc[0, 0:2] = np.nan  # Still 1 value in batch 1
        batch = np.array([1, 1, 1, 2, 2, 2])
        block = batch.copy()
        result = spotting_missing_values(data, batch, block, needed_values=1)
        assert result[0] == (1, 2)

    def test_needed_values_2_stricter(self):
        """needed_values=2 is stricter than 1."""
        data = pd.DataFrame(np.ones((3, 6)))
        data.iloc[0, 0:2] = np.nan  # Only 1 value in batch 1
        batch = np.array([1, 1, 1, 2, 2, 2])
        result_nv1 = spotting_missing_values(data, batch, batch, needed_values=1)
        result_nv2 = spotting_missing_values(data, batch, batch, needed_values=2)
        assert result_nv1[0] == (1, 2)  # 1 value in batch 1 suffices
        assert result_nv2[0] == (2,)    # Not enough in batch 1

    def test_three_batches_partial_missing(self):
        """Feature present in only 2 of 3 batches."""
        data = pd.DataFrame(np.ones((2, 9)))
        data.iloc[0, 6:] = np.nan  # Missing batch 3
        batch = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3])
        block = batch.copy()
        result = spotting_missing_values(data, batch, block, needed_values=2)
        assert result[0] == (1, 2)
        assert result[1] == (1, 2, 3)


# ===================================================================
# 9. Splitting + rebuild integration
# ===================================================================

class TestSplittingRebuild:
    def test_no_missing_single_group(self):
        """Complete data → one sub-df, result matches direct combat."""
        rng = np.random.default_rng(60)
        data = pd.DataFrame(
            rng.normal(10, 2, size=(10, 6)),
            index=[f"p_{i}" for i in range(10)],
            columns=[f"s_{j}" for j in range(6)],
        )
        data.iloc[:, 3:] += 3.0
        batch = np.array([1, 1, 1, 2, 2, 2])
        block = batch.copy()
        affiliation = spotting_missing_values(data, batch, block, needed_values=2)

        sub_dfs = splitting(affiliation, data, batch, block,
                            algorithm="ComBat", combat_mode=2)
        result = rebuild(sub_dfs)

        # Should match direct combat
        direct = adjust_combat(data, batch, mode=2)
        np.testing.assert_allclose(result.values, direct.values, atol=1e-12)

    def test_partial_missing_produces_nans(self):
        """Features missing a batch appear with NaN in that batch's columns."""
        rng = np.random.default_rng(61)
        data = pd.DataFrame(
            rng.normal(10, 2, size=(5, 9)),
            index=[f"p_{i}" for i in range(5)],
            columns=[f"s_{j}" for j in range(9)],
        )
        data.iloc[0, 6:] = np.nan  # Feature 0 missing batch 3
        batch = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3])
        block = batch.copy()
        affiliation = spotting_missing_values(data, batch, block, needed_values=2)

        sub_dfs = splitting(affiliation, data, batch, block,
                            algorithm="ComBat", combat_mode=2)
        result = rebuild(sub_dfs)

        # Feature 0: NaN in batch 3 columns
        assert np.isnan(result.iloc[0, 6:]).all()
        # Feature 0: values in batches 1-2
        assert not np.isnan(result.iloc[0, :6]).any()

    def test_all_missing_feature_stays_nan(self):
        """Completely NaN feature → stays all NaN after splitting."""
        rng = np.random.default_rng(62)
        data = pd.DataFrame(
            rng.normal(10, 2, size=(5, 6)),
            index=[f"p_{i}" for i in range(5)],
            columns=[f"s_{j}" for j in range(6)],
        )
        data.iloc[0, :] = np.nan
        batch = np.array([1, 1, 1, 2, 2, 2])
        block = batch.copy()
        affiliation = spotting_missing_values(data, batch, block, needed_values=2)

        sub_dfs = splitting(affiliation, data, batch, block,
                            algorithm="limma")
        result = rebuild(sub_dfs)
        assert np.isnan(result.iloc[0]).all()

    def test_limma_through_splitting(self):
        """limma adjustment works through full splitting pipeline."""
        rng = np.random.default_rng(63)
        data = pd.DataFrame(
            rng.normal(10, 2, size=(10, 6)),
            index=[f"p_{i}" for i in range(10)],
            columns=[f"s_{j}" for j in range(6)],
        )
        data.iloc[:, 3:] += 3.0
        batch = np.array([1, 1, 1, 2, 2, 2])
        block = batch.copy()
        affiliation = spotting_missing_values(data, batch, block, needed_values=2)

        sub_dfs = splitting(affiliation, data, batch, block, algorithm="limma")
        result = rebuild(sub_dfs)

        direct = adjust_limma(data, batch)
        np.testing.assert_allclose(result.values, direct.values, atol=1e-12)


# ===================================================================
# 10. Singleton batch (R forces mean_only)
# ===================================================================

@pytest.mark.skipif(
    not _fixture_exists("singleton_combat_mode2.tsv"),
    reason="Singleton fixtures not generated",
)
class TestSingletonBatch:
    """R forces mean_only=TRUE when a batch has 1 sample.

    Parametric modes (1,2) collapse to the same result; likewise
    nonparametric (3,4).  We keep only mode 2 and mode 4 fixtures.
    """

    @pytest.fixture(autouse=True)
    def _load(self):
        self.data = _load_tsv("singleton_input.tsv")
        self.batch = _load_batch("singleton_batch.csv")

    @pytest.mark.parametrize("mode", [2, 4])
    def test_mean_only_matches_r(self, mode):
        """Our mean_only modes should match R's singleton output."""
        expected = _load_tsv(f"singleton_combat_mode{mode}.tsv")
        params = _MODE_PARAMS[mode]
        result = combat(self.data, self.batch, **params)
        np.testing.assert_allclose(
            result, expected, rtol=1e-4, atol=1e-6,
            err_msg=f"Singleton mode {mode} mismatch",
        )
