"""Comprehensive edge-case, failure-mode, and R-concordance tests.

Organized into:
  1.  ComBat R concordance: varied scenarios (large, unbalanced, minimal, etc.)
  2.  limma R concordance: varied scenarios
  3.  HarmonizR pipeline R concordance: large, sparse, medium limma,
      high-missingness, and needed_values invariance
  4.  ComBat failure modes and edge cases
  5.  limma failure modes and edge cases
  6.  Pipeline failure modes and edge cases
  7.  Numerical stability and determinism
  8.  spotting / splitting unit tests
  9.  Splitting integration
  10. Singleton batch (R forces mean_only)
  11. needed_values parameter (Step 3)
  12. NaN propagation audit (Step 4)

All R reference values are generated by generate_edgecase_fixtures.R.

Tolerance reference (Section 5.3)
----------------------------------
Observed maximum absolute difference between Python and R outputs:

  Mode 1 (parametric, location+scale)     rtol ~2e-5, atol ~1e-5
    Cause: iterative EM solver (_it_sol) reaches a different fixed point
    within the same tolerance window as R's optim().  Every non-parametric
    mode and the mean-only modes use closed-form or single-pass formulas
    so agreement is at double-precision machine epsilon.

  Mode 2 (parametric, location only)      rtol ~1e-9, atol ~1e-9
  Mode 3 (non-parametric, location+scale) rtol ~2e-4, atol ~1e-4
    Cause: Monte-Carlo integration (_int_eprior) with finite n draws;
    R uses a different random stream so the estimates differ slightly.
  Mode 4 (non-parametric, location only)  rtol ~1e-9, atol ~1e-9

  limma (OLS, no iteration)               rtol ~1e-9, atol ~1e-9

These tolerances are the reference for future changes; tighter values
should not be used without understanding the cause.
"""

from __future__ import annotations

from pathlib import Path
from typing import TypedDict

import numpy as np
import pandas as pd
import pytest

from harmonizepy.affiliation import build_affiliation_list
from harmonizepy.combat import combat
from harmonizepy.combat_wrapper import adjust_combat
from harmonizepy.core import harmonize
from harmonizepy.limma_wrapper import adjust_limma, remove_batch_effect
from harmonizepy.splitting import splitting

# ---------------------------------------------------------------------------
# Fixture helpers
# ---------------------------------------------------------------------------

FIXTURE_DIR = Path(__file__).parent / "fixtures"


def _load_tsv(name: str) -> np.ndarray:
    df = pd.read_csv(FIXTURE_DIR / name, sep="\t", index_col=0)
    return df.to_numpy()


def _load_tsv_df(name: str) -> pd.DataFrame:
    return pd.read_csv(FIXTURE_DIR / name, sep="\t", index_col=0)


def _load_batch(name: str) -> np.ndarray:
    return pd.read_csv(FIXTURE_DIR / name)["batch"].to_numpy()


def _fixture_exists(name: str) -> bool:
    return (FIXTURE_DIR / name).exists()


# ===================================================================
# 1. ComBat vs R sva::ComBat: extended scenarios
# ===================================================================


class _DatasetSpec(TypedDict):
    input: str
    batch: str
    modes: list[int]
    fixture: str


_DATASETS: dict[str, _DatasetSpec] = {
    "large": {
        "input": "large_input.tsv",
        "batch": "large_batch.csv",
        "modes": [1, 2, 3, 4],
        "fixture": "large_combat_mode{}.tsv",
    },
    "unbalanced": {
        "input": "unbalanced_input.tsv",
        "batch": "unbalanced_batch.csv",
        "modes": [1, 2, 3, 4],
        "fixture": "unbalanced_combat_mode{}.tsv",
    },
    "minimal": {
        "input": "minimal_input.tsv",
        "batch": "minimal_batch.csv",
        # mode 1 fails in R too (2 features, convergence error), skip it
        # mode 4 is identical to mode 2 for this tiny dataset
        "modes": [2, 3],
        "fixture": "minimal_combat_mode{}.tsv",
    },
    "highvar": {
        "input": "highvar_input.tsv",
        "batch": "highvar_batch.csv",
        "modes": [1, 2, 3, 4],
        "fixture": "highvar_combat_mode{}.tsv",
    },
    "nearconstant": {
        "input": "nearconstant_input.tsv",
        "batch": "nearconstant_batch.csv",
        # Only mean_only modes (2, 4) for near-constant features
        "modes": [2, 4],
        "fixture": "nearconstant_combat_mode{}.tsv",
    },
    "negative": {
        "input": "negative_input.tsv",
        "batch": "negative_batch.csv",
        "modes": [1, 2, 3, 4],
        "fixture": "negative_combat_mode{}.tsv",
    },
    "wide": {
        "input": "wide_input.tsv",
        "batch": "wide_batch.csv",
        "modes": [1, 2, 3, 4],
        "fixture": "wide_combat_mode{}.tsv",
    },
}

_MODE_PARAMS = {
    1: {"par_prior": True, "mean_only": False},
    2: {"par_prior": True, "mean_only": True},
    3: {"par_prior": False, "mean_only": False},
    4: {"par_prior": False, "mean_only": True},
}


def _combat_test_cases():
    """Yield (dataset_name, mode) tuples for parametrize."""
    for name, spec in _DATASETS.items():
        for mode in spec["modes"]:
            fixture = spec["fixture"].format(mode)
            if _fixture_exists(fixture):
                yield pytest.param(name, mode, id=f"{name}-mode{mode}")


@pytest.mark.skipif(
    not _fixture_exists("large_combat_mode1.tsv"),
    reason="Edge-case R fixtures not generated",
)
class TestCombatRConcordanceExtended:
    """ComBat output must match R sva::ComBat across diverse scenarios."""

    @pytest.mark.parametrize("dataset,mode", list(_combat_test_cases()))
    def test_vs_r_sva(self, dataset, mode):
        spec = _DATASETS[dataset]
        data = _load_tsv(spec["input"])
        batch = _load_batch(spec["batch"])
        expected = _load_tsv(spec["fixture"].format(mode))
        params = _MODE_PARAMS[mode]

        result = combat(data, batch, **params)

        # Mode 1 (parametric iterative) has slightly higher tolerance
        rtol = 1e-4 if mode == 1 else 1e-6
        atol = 1e-5 if mode == 1 else 1e-8
        # Nonparametric modes on large data can have slightly more divergence
        if mode == 3 and dataset == "large":
            rtol = 5e-4
            atol = 1e-4

        # R produces NaN for near-constant features (pooled var ≈ 0);
        # our implementation clamps var_pooled > 0 and returns numbers.
        # Compare only where R produced non-NaN, then verify R-NaN rows
        # are from near-constant features (low within-batch variance).
        r_nan_mask = np.isnan(expected)
        if r_nan_mask.any():
            # Rows where R says NaN, verify they have near-zero residual var
            nan_rows = np.where(r_nan_mask.any(axis=1))[0]
            unique_b = np.unique(batch)
            for r in nan_rows:
                # Check within-batch variance (what R actually uses for pooled var)
                within_vars = [
                    data[r, batch == b].var(ddof=1) for b in unique_b if (batch == b).sum() > 1
                ]
                max_within_var = max(within_vars) if within_vars else 0
                assert max_within_var < 0.1, (
                    f"R output NaN for row {r} but max within-batch var={max_within_var:.2e}"
                )
            # Compare non-NaN portion
            valid = ~r_nan_mask
            if valid.any():
                np.testing.assert_allclose(
                    result[valid],
                    expected[valid],
                    rtol=rtol,
                    atol=atol,
                    err_msg=f"{dataset} mode {mode}: mismatch vs R sva::ComBat",
                )
        else:
            np.testing.assert_allclose(
                result,
                expected,
                rtol=rtol,
                atol=atol,
                err_msg=f"{dataset} mode {mode}: mismatch vs R sva::ComBat",
            )

    @pytest.mark.parametrize("dataset,mode", list(_combat_test_cases()))
    def test_shape_preserved(self, dataset, mode):
        spec = _DATASETS[dataset]
        data = _load_tsv(spec["input"])
        batch = _load_batch(spec["batch"])
        result = combat(data, batch, **_MODE_PARAMS[mode])
        assert result.shape == data.shape

    @pytest.mark.parametrize("dataset,mode", list(_combat_test_cases()))
    def test_no_nan_in_output(self, dataset, mode):
        spec = _DATASETS[dataset]
        data = _load_tsv(spec["input"])
        batch = _load_batch(spec["batch"])
        result = combat(data, batch, **_MODE_PARAMS[mode])
        assert not np.isnan(result).any(), f"NaN in {dataset} mode {mode}"

    @pytest.mark.parametrize("dataset,mode", list(_combat_test_cases()))
    def test_batch_means_converge(self, dataset, mode):
        """After correction, batch means should be more similar."""
        spec = _DATASETS[dataset]
        data = _load_tsv(spec["input"])
        batch = _load_batch(spec["batch"])
        result = combat(data, batch, **_MODE_PARAMS[mode])

        unique_b = np.unique(batch)
        means_before = [data[:, batch == b].mean() for b in unique_b]
        means_after = [result[:, batch == b].mean() for b in unique_b]
        spread_before = max(means_before) - min(means_before)
        spread_after = max(means_after) - min(means_after)
        assert spread_after < spread_before + 1e-10, (
            f"{dataset} mode {mode}: spread not reduced {spread_before:.4f} → {spread_after:.4f}"
        )


# ===================================================================
# 2. limma vs R limma::removeBatchEffect: extended scenarios
# ===================================================================

_LIMMA_DATASETS: dict[str, dict[str, str]] = {
    "large": {"input": "large_input.tsv", "batch": "large_batch.csv", "fixture": "large_limma.tsv"},
    "unbalanced": {
        "input": "unbalanced_input.tsv",
        "batch": "unbalanced_batch.csv",
        "fixture": "unbalanced_limma.tsv",
    },
    "minimal": {
        "input": "minimal_input.tsv",
        "batch": "minimal_batch.csv",
        "fixture": "minimal_limma.tsv",
    },
    "highvar": {
        "input": "highvar_input.tsv",
        "batch": "highvar_batch.csv",
        "fixture": "highvar_limma.tsv",
    },
    "nearconstant": {
        "input": "nearconstant_input.tsv",
        "batch": "nearconstant_batch.csv",
        "fixture": "nearconstant_limma.tsv",
    },
    "negative": {
        "input": "negative_input.tsv",
        "batch": "negative_batch.csv",
        "fixture": "negative_limma.tsv",
    },
    "wide": {"input": "wide_input.tsv", "batch": "wide_batch.csv", "fixture": "wide_limma.tsv"},
}


def _limma_test_cases():
    for name, spec in _LIMMA_DATASETS.items():
        if _fixture_exists(spec["fixture"]):
            yield pytest.param(name, id=name)


@pytest.mark.skipif(
    not _fixture_exists("large_limma.tsv"),
    reason="Edge-case R fixtures not generated",
)
class TestLimmaRConcordanceExtended:
    """limma output must match R limma::removeBatchEffect."""

    @pytest.mark.parametrize("dataset", list(_limma_test_cases()))
    def test_vs_r_limma(self, dataset):
        spec = _LIMMA_DATASETS[dataset]
        data = _load_tsv(spec["input"])
        batch = _load_batch(spec["batch"])
        expected = _load_tsv(spec["fixture"])
        result = remove_batch_effect(data, batch)

        np.testing.assert_allclose(
            result,
            expected,
            rtol=1e-10,
            atol=1e-10,
            err_msg=f"{dataset}: mismatch vs R limma",
        )

    @pytest.mark.parametrize("dataset", list(_limma_test_cases()))
    def test_shape_no_nan(self, dataset):
        spec = _LIMMA_DATASETS[dataset]
        data = _load_tsv(spec["input"])
        batch = _load_batch(spec["batch"])
        result = remove_batch_effect(data, batch)
        assert result.shape == data.shape
        assert not np.isnan(result).any()


# ===================================================================
# 3. HarmonizR pipeline R concordance: large, sparse, and medium limma
# ===================================================================


@pytest.mark.skipif(
    not _fixture_exists("large_combat_mode1.tsv"),
    reason="Large R fixtures not generated",
)
class TestHarmonizRLargeConcordance:
    """Full pipeline vs R sva::ComBat for large (no-missing) dataset."""

    @pytest.fixture(autouse=True)
    def _load(self):
        self.data = _load_tsv_df("large_input.tsv")
        batch_csv = pd.read_csv(FIXTURE_DIR / "large_batch.csv")
        self.desc = batch_csv

    @pytest.mark.parametrize("mode", [1, 2, 3, 4])
    def test_combat_modes(self, mode):
        expected = _load_tsv(f"large_combat_mode{mode}.tsv")
        result = harmonize(
            self.data,
            self.desc,
            algorithm="ComBat",
            combat_mode=mode,
        )
        rtol = 1e-4 if mode in (1, 3) else 1e-6
        atol = 1e-5 if mode in (1, 3) else 1e-8
        # Large nonparametric needs a bit more tolerance
        if mode == 3:
            rtol = 5e-4
            atol = 1e-4
        np.testing.assert_allclose(
            result.values,
            expected,
            rtol=rtol,
            atol=atol,
            err_msg=f"Large HarmonizR ComBat mode {mode}",
        )


@pytest.mark.skipif(
    not _fixture_exists("sparse_harmonizr_combat_mode1.tsv"),
    reason="Sparse HarmonizR fixtures not generated",
)
class TestHarmonizRSparseConcordance:
    """Full pipeline vs R HarmonizR for sparse (50% batches missing)."""

    @pytest.fixture(autouse=True)
    def _load(self):
        self.data = _load_tsv_df("sparse_input.tsv")
        batch_csv = pd.read_csv(FIXTURE_DIR / "sparse_batch.csv")
        self.desc = batch_csv

    @pytest.mark.parametrize("mode", [1, 2, 3, 4])
    def test_combat_modes(self, mode):
        expected_df = _load_tsv_df(f"sparse_harmonizr_combat_mode{mode}.tsv")
        result = harmonize(
            self.data,
            self.desc,
            algorithm="ComBat",
            combat_mode=mode,
        )
        # Align by shared features (index) and columns
        shared_idx = result.index.intersection(expected_df.index)
        shared_cols = result.columns.intersection(expected_df.columns)
        r = result.loc[shared_idx, shared_cols].values
        e = expected_df.loc[shared_idx, shared_cols].values

        # Both have NaN in the same places
        nan_mask = np.isnan(e)
        assert np.isnan(r[nan_mask]).all(), "Expected NaN where R has NaN"

        # Compare non-NaN values
        valid = ~nan_mask
        if valid.any():
            rtol = 5e-4 if mode in (1, 3) else 1e-5
            np.testing.assert_allclose(
                r[valid],
                e[valid],
                rtol=rtol,
                atol=1e-4,
                err_msg=f"Sparse HarmonizR ComBat mode {mode}",
            )


@pytest.mark.skipif(
    not _fixture_exists("medium_harmonizr_limma.tsv"),
    reason="Medium HarmonizR limma fixture not generated",
)
class TestHarmonizRMediumLimma:
    """Pipeline vs R HarmonizR for medium dataset with limma."""

    def test_limma(self):
        data = _load_tsv_df("medium_input.tsv")
        batch_csv = pd.read_csv(FIXTURE_DIR / "medium_batch.csv")
        expected_df = _load_tsv_df("medium_harmonizr_limma.tsv")
        result = harmonize(data, batch_csv, algorithm="limma")

        shared_idx = result.index.intersection(expected_df.index)
        shared_cols = result.columns.intersection(expected_df.columns)
        r = result.loc[shared_idx, shared_cols].values
        e = expected_df.loc[shared_idx, shared_cols].values

        nan_mask = np.isnan(e)
        assert np.isnan(r[nan_mask]).all(), "Expected NaN where R has NaN"

        valid = ~nan_mask
        if valid.any():
            np.testing.assert_allclose(
                r[valid],
                e[valid],
                rtol=1e-8,
                atol=1e-8,
                err_msg="Medium HarmonizR limma",
            )


@pytest.mark.skipif(
    not _fixture_exists("highmiss_harmonizr_combat_mode1.tsv"),
    reason="High-missingness R fixtures not generated",
)
class TestHarmonizRHighMissConcordance:
    """Full pipeline vs R HarmonizR for high-missingness dataset.

    Dataset: 50 proteins x 9 samples x 3 batches (3 each), ~65%
    structural missing (one whole batch absent per feature).
    """

    @pytest.fixture(autouse=True)
    def _load(self):
        self.data = _load_tsv_df("highmiss_input.tsv")
        self.desc = pd.read_csv(FIXTURE_DIR / "highmiss_batch.csv")

    @pytest.mark.parametrize("mode", [1, 2, 3, 4])
    def test_combat_modes(self, mode):
        expected_df = _load_tsv_df(f"highmiss_harmonizr_combat_mode{mode}.tsv")
        result = harmonize(
            self.data,
            self.desc,
            algorithm="ComBat",
            combat_mode=mode,
        )
        shared_idx = result.index.intersection(expected_df.index)
        shared_cols = result.columns.intersection(expected_df.columns)
        r = result.loc[shared_idx, shared_cols].values
        e = expected_df.loc[shared_idx, shared_cols].values

        nan_mask = np.isnan(e)
        assert np.isnan(r[nan_mask]).all(), "Expected NaN where R has NaN"
        assert not np.isnan(r[~nan_mask]).any(), "No extra NaN in Python output"

        valid = ~nan_mask
        if valid.any():
            rtol = 5e-4 if mode in (1, 3) else 1e-5
            np.testing.assert_allclose(
                r[valid],
                e[valid],
                rtol=rtol,
                atol=1e-4,
                err_msg=f"High-miss HarmonizR ComBat mode {mode}",
            )

    def test_limma(self):
        expected_df = _load_tsv_df("highmiss_harmonizr_limma.tsv")
        result = harmonize(self.data, self.desc, algorithm="limma")

        shared_idx = result.index.intersection(expected_df.index)
        shared_cols = result.columns.intersection(expected_df.columns)
        r = result.loc[shared_idx, shared_cols].values
        e = expected_df.loc[shared_idx, shared_cols].values

        nan_mask = np.isnan(e)
        assert np.isnan(r[nan_mask]).all(), "Expected NaN where R has NaN"
        assert not np.isnan(r[~nan_mask]).any(), "No extra NaN in Python output"

        valid = ~nan_mask
        if valid.any():
            np.testing.assert_allclose(
                r[valid],
                e[valid],
                rtol=1e-8,
                atol=1e-8,
                err_msg="High-miss HarmonizR limma",
            )


@pytest.mark.skipif(
    not _fixture_exists("medium_harmonizr_combat_mode1.tsv"),
    reason="Medium HarmonizR fixtures not generated",
)
class TestNeededValuesRConcordance:
    """Pipeline output at nv=1 and nv=3 matches R at nv=2 for medium.

    The medium dataset has whole-batch structural missingness with 4
    samples per batch.  For any threshold 1 <= nv <= 4, a batch with
    all 4 samples present always satisfies the threshold, and a batch
    with 0 samples present never satisfies it.  Consequently nv=1, 2,
    and 3 all produce identical affiliation patterns and identical
    adjusted output.  These tests confirm that different explicit
    thresholds do not break concordance when the affiliation is
    unchanged.
    """

    @pytest.fixture(autouse=True)
    def _load(self):
        self.data = _load_tsv_df("medium_input.tsv")
        self.desc = pd.read_csv(FIXTURE_DIR / "medium_batch.csv")

    @pytest.mark.parametrize("nv", [1, 3])
    @pytest.mark.parametrize("mode", [1, 2, 3, 4])
    def test_combat_nv_equivalent_to_r(self, mode, nv):
        """nv=1 and nv=3 both match the R fixture (same as nv=2)."""
        expected_df = _load_tsv_df(f"medium_harmonizr_combat_mode{mode}.tsv")
        result = harmonize(
            self.data,
            self.desc,
            algorithm="ComBat",
            combat_mode=mode,
            needed_values=nv,
        )
        shared_idx = result.index.intersection(expected_df.index)
        shared_cols = result.columns.intersection(expected_df.columns)
        r = result.loc[shared_idx, shared_cols].values
        e = expected_df.loc[shared_idx, shared_cols].values

        nan_mask = np.isnan(e)
        assert np.isnan(r[nan_mask]).all(), "Expected NaN where R has NaN"
        assert not np.isnan(r[~nan_mask]).any(), "No extra NaN in Python output"

        valid = ~nan_mask
        if valid.any():
            rtol = 5e-4 if mode in (1, 3) else 1e-5
            np.testing.assert_allclose(
                r[valid],
                e[valid],
                rtol=rtol,
                atol=1e-4,
                err_msg=f"Medium nv={nv} ComBat mode {mode}",
            )

    @pytest.mark.parametrize("nv", [1, 3])
    def test_limma_nv_equivalent_to_r(self, nv):
        """nv=1 and nv=3 both match the R limma fixture (same as nv=2)."""
        expected_df = _load_tsv_df("medium_harmonizr_limma.tsv")
        result = harmonize(
            self.data,
            self.desc,
            algorithm="limma",
            needed_values=nv,
        )
        shared_idx = result.index.intersection(expected_df.index)
        shared_cols = result.columns.intersection(expected_df.columns)
        r = result.loc[shared_idx, shared_cols].values
        e = expected_df.loc[shared_idx, shared_cols].values

        nan_mask = np.isnan(e)
        assert np.isnan(r[nan_mask]).all(), "Expected NaN where R has NaN"
        assert not np.isnan(r[~nan_mask]).any(), "No extra NaN in Python output"

        valid = ~nan_mask
        if valid.any():
            np.testing.assert_allclose(
                r[valid],
                e[valid],
                rtol=1e-8,
                atol=1e-8,
                err_msg=f"Medium nv={nv} limma",
            )


# ===================================================================
# 4. ComBat failure modes and edge cases
# ===================================================================


class TestCombatFailureModes:
    """Verify combat raises clear errors on bad input."""

    def test_1d_input_rejected(self):
        with pytest.raises(ValueError, match="2-D"):
            combat(np.array([1.0, 2.0, 3.0]), np.array([0, 0, 1]))

    def test_3d_input_rejected(self):
        with pytest.raises(ValueError, match="2-D"):
            combat(np.zeros((2, 3, 4)), np.array([0, 0, 1]))

    def test_nan_raises(self):
        data = np.array([[1.0, 2.0, 3.0, 4.0], [np.nan, 6.0, 7.0, 8.0]])
        with pytest.raises(ValueError, match="NaN"):
            combat(data, np.array([0, 0, 1, 1]))

    def test_single_feature_rejected(self):
        with pytest.raises(ValueError, match="at least 2 features"):
            combat(np.array([[1.0, 2.0, 3.0, 4.0]]), np.array([0, 0, 1, 1]))

    def test_batch_length_mismatch(self):
        data = np.random.default_rng(1).normal(size=(5, 6))
        with pytest.raises(ValueError, match="batch length"):
            combat(data, np.array([0, 0, 1]))

    def test_invalid_ref_batch(self):
        data = np.random.default_rng(1).normal(size=(5, 6))
        batch = np.array([0, 0, 0, 1, 1, 1])
        with pytest.raises(ValueError, match="ref_batch"):
            combat(data, batch, ref_batch=99)

    def test_single_batch_returns_copy(self):
        """Single batch → data returned unchanged."""
        data = np.random.default_rng(2).normal(10, 2, size=(10, 4))
        batch = np.array([0, 0, 0, 0])
        result = combat(data, batch)
        np.testing.assert_array_equal(result, data)
        # Must be a copy, not the same object
        assert result is not data

    def test_empty_features_many_samples(self):
        """Two features, many samples. Should not crash."""
        rng = np.random.default_rng(3)
        data = rng.normal(10, 1, size=(2, 20))
        data[:, 10:] += 3.0
        batch = np.array([0] * 10 + [1] * 10)
        result = combat(data, batch, par_prior=True, mean_only=True)
        assert result.shape == data.shape
        assert not np.isnan(result).any()


class TestCombatEdgeCaseBehavior:
    """Behavioral edge cases, not errors but tricky inputs."""

    def test_noncontiguous_labels(self):
        """Labels like [5, 5, 10, 10] work via remapping."""
        rng = np.random.default_rng(10)
        data = rng.normal(10, 2, size=(20, 8))
        data[:, 4:] += 3.0
        batch = np.array([5, 5, 5, 5, 10, 10, 10, 10])
        result = combat(data, batch)
        assert result.shape == data.shape
        assert not np.isnan(result).any()

    def test_string_int_labels(self):
        """Batch labels as strings representing ints should work after conversion."""
        rng = np.random.default_rng(11)
        data = rng.normal(10, 2, size=(10, 6))
        data[:, 3:] += 2.0
        batch = np.array([1, 1, 1, 2, 2, 2])
        result = combat(data, batch)
        assert result.shape == data.shape

    def test_ref_batch_preserves_reference(self):
        """Reference batch data must be exactly unchanged."""
        rng = np.random.default_rng(12)
        data = rng.normal(10, 2, size=(20, 9))
        data[:, 3:6] += 3.0
        data[:, 6:] -= 2.0
        batch = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2])
        for ref_b in [0, 1, 2]:
            result = combat(data, batch, ref_batch=ref_b)
            ref_cols = batch == ref_b
            np.testing.assert_array_equal(
                result[:, ref_cols],
                data[:, ref_cols],
                err_msg=f"ref_batch={ref_b}: reference data changed",
            )

    def test_ref_batch_with_noncontiguous_labels(self):
        """ref_batch refers to original labels, not remapped ones."""
        rng = np.random.default_rng(13)
        data = rng.normal(10, 2, size=(15, 8))
        data[:, 4:] += 4.0
        batch = np.array([10, 10, 10, 10, 20, 20, 20, 20])
        result = combat(data, batch, ref_batch=10)
        ref_cols = batch == 10
        np.testing.assert_array_equal(result[:, ref_cols], data[:, ref_cols])

    def test_identical_batches_no_change(self):
        """If batches have no real effect, output should ≈ input."""
        rng = np.random.default_rng(14)
        data = rng.normal(10, 1, size=(30, 8))
        batch = np.array([0, 0, 0, 0, 1, 1, 1, 1])
        result = combat(data, batch, par_prior=True, mean_only=True)
        # Should be very close to input since no real batch effect
        np.testing.assert_allclose(
            result, data, atol=1.0, err_msg="Large change with no real batch effect"
        )

    def test_all_negative_data(self):
        """Negative data should work fine (e.g., log2FC)."""
        rng = np.random.default_rng(15)
        data = rng.normal(-5, 2, size=(20, 8))
        data[:, 4:] -= 3.0
        batch = np.array([0, 0, 0, 0, 1, 1, 1, 1])
        result = combat(data, batch)
        assert result.shape == data.shape
        assert not np.isnan(result).any()

    def test_very_large_values(self):
        """Data with very large values should not overflow."""
        rng = np.random.default_rng(16)
        data = rng.normal(1e6, 1e4, size=(10, 6))
        data[:, 3:] += 1e5
        batch = np.array([0, 0, 0, 1, 1, 1])
        result = combat(data, batch, par_prior=True, mean_only=True)
        assert not np.isnan(result).any()
        assert np.isfinite(result).all()

    def test_very_small_values(self):
        """Near-zero data should not cause division issues."""
        rng = np.random.default_rng(17)
        data = rng.normal(1e-10, 1e-12, size=(10, 6))
        data[:, 3:] += 1e-10
        batch = np.array([0, 0, 0, 1, 1, 1])
        result = combat(data, batch, par_prior=True, mean_only=True)
        assert not np.isnan(result).any()
        assert np.isfinite(result).all()

    def test_many_batches(self):
        """Works with many batches (10)."""
        rng = np.random.default_rng(18)
        n_batches = 10
        n_per = 3
        data = rng.normal(10, 2, size=(20, n_batches * n_per))
        batch = np.repeat(range(n_batches), n_per)
        for b in range(n_batches):
            data[:, batch == b] += rng.normal(0, 2)
        result = combat(data, batch, par_prior=True, mean_only=True)
        assert result.shape == data.shape
        assert not np.isnan(result).any()

    def test_wrapper_mode_dispatch(self):
        """adjust_combat correctly dispatches all 4 modes."""
        rng = np.random.default_rng(19)
        df = pd.DataFrame(
            rng.normal(10, 2, size=(15, 8)),
            index=[f"p_{i}" for i in range(15)],
            columns=[f"s_{j}" for j in range(8)],
        )
        df.iloc[:, 4:] += 3.0
        batch = np.array([0, 0, 0, 0, 1, 1, 1, 1])
        for mode in [1, 2, 3, 4]:
            result = adjust_combat(df, batch, mode=mode)
            assert isinstance(result, pd.DataFrame)
            assert list(result.index) == list(df.index)
            assert list(result.columns) == list(df.columns)

    def test_wrapper_single_batch_passthrough(self):
        """adjust_combat with single batch returns copy."""
        df = pd.DataFrame(
            np.random.default_rng(20).normal(size=(5, 4)),
            index=[f"p_{i}" for i in range(5)],
            columns=[f"s_{j}" for j in range(4)],
        )
        batch = np.array([1, 1, 1, 1])
        result = adjust_combat(df, batch, mode=1)
        pd.testing.assert_frame_equal(result, df)


# ===================================================================
# 5. limma failure modes and edge cases
# ===================================================================


class TestLimmaFailureModes:
    """limma raises clear errors on invalid inputs.

    Failure condition: bad input is silently accepted or produces
    a misleading exception type/message.
    """
    def test_1d_rejected(self):
        with pytest.raises(ValueError, match="2-D"):
            remove_batch_effect(np.array([1, 2, 3]), np.array([0, 0, 1]))

    def test_nan_rejected(self):
        data = np.array([[1.0, np.nan], [3.0, 4.0]])
        with pytest.raises(ValueError, match="NaN"):
            remove_batch_effect(data, np.array([0, 1]))

    def test_batch_length_mismatch(self):
        data = np.random.default_rng(1).normal(size=(5, 4))
        with pytest.raises(ValueError, match="batch length"):
            remove_batch_effect(data, np.array([0, 1]))

    def test_single_batch_passthrough(self):
        data = np.random.default_rng(2).normal(size=(5, 4))
        batch = np.array([0, 0, 0, 0])
        result = remove_batch_effect(data, batch)
        np.testing.assert_array_equal(result, data)
        assert result is not data


class TestLimmaEdgeCaseBehavior:
    """limma handles edge cases without crashing or producing NaN.

    Failure condition: an unusual input shape or value causes
    a crash or NaN in the output.
    """
    def test_many_batches(self):
        """limma handles 5 batches."""
        rng = np.random.default_rng(30)
        data = rng.normal(10, 2, size=(20, 15))
        batch = np.repeat(range(5), 3)
        for b in range(5):
            data[:, batch == b] += rng.normal(0, 2)
        result = remove_batch_effect(data, batch)
        assert result.shape == data.shape
        assert not np.isnan(result).any()

    def test_negative_data(self):
        rng = np.random.default_rng(31)
        data = rng.normal(-5, 3, size=(15, 6))
        data[:, 3:] -= 4.0
        batch = np.array([0, 0, 0, 1, 1, 1])
        result = remove_batch_effect(data, batch)
        assert not np.isnan(result).any()

    def test_adjust_limma_preserves_index(self):
        """DataFrame wrapper preserves index and columns."""
        rng = np.random.default_rng(32)
        df = pd.DataFrame(
            rng.normal(10, 2, size=(8, 6)),
            index=[f"gene_{i}" for i in range(8)],
            columns=[f"samp_{j}" for j in range(6)],
        )
        df.iloc[:, 3:] += 2.0
        batch = np.array([0, 0, 0, 1, 1, 1])
        result = adjust_limma(df, batch)
        assert list(result.index) == list(df.index)
        assert list(result.columns) == list(df.columns)

    def test_unbalanced_batches(self):
        """Unbalanced batches (2, 5, 3 samples)."""
        rng = np.random.default_rng(33)
        data = rng.normal(10, 2, size=(20, 10))
        batch = np.array([0, 0, 1, 1, 1, 1, 1, 2, 2, 2])
        data[:, batch == 1] += 2.0
        data[:, batch == 2] -= 1.5
        result = remove_batch_effect(data, batch)
        assert result.shape == data.shape
        assert not np.isnan(result).any()

    def test_large_scale(self):
        """500 features x 30 samples. Must not be slow or unstable."""
        rng = np.random.default_rng(34)
        data = rng.normal(10, 2, size=(500, 30))
        batch = np.repeat(range(5), 6)
        for b in range(5):
            data[:, batch == b] += rng.normal(0, 3)
        result = remove_batch_effect(data, batch)
        assert not np.isnan(result).any()
        assert np.isfinite(result).all()

    def test_2_features_2_samples_per_batch(self):
        """Minimal valid limma case."""
        data = np.array([[1.0, 2.0, 5.0, 6.0], [3.0, 4.0, 7.0, 8.0]])
        batch = np.array([0, 0, 1, 1])
        result = remove_batch_effect(data, batch)
        assert result.shape == (2, 4)
        assert not np.isnan(result).any()


# ===================================================================
# 6. Pipeline failure modes and edge cases
# ===================================================================


class TestPipelineFailureModes:
    """Pipeline raises clear errors on invalid inputs and edge cases.

    Failure condition: bad input silently passes through or crashes
    with an uninformative exception.
    """
    def test_mismatched_samples(self):
        """Description has different number of samples than data."""
        data = pd.DataFrame(
            np.random.default_rng(1).normal(size=(5, 4)),
            columns=["s1", "s2", "s3", "s4"],
        )
        desc = pd.DataFrame(
            {
                "ID": ["s1", "s2", "s3"],
                "sample": [1, 2, 3],
                "batch": [1, 1, 2],
            }
        )
        with pytest.raises(ValueError, match=r"(?i)sample"):
            harmonize(data, desc)

    def test_all_missing_feature(self):
        """Feature with all NaN should appear as NaN in output."""
        data = pd.DataFrame(
            np.random.default_rng(2).normal(10, 1, size=(5, 6)),
            index=[f"p_{i}" for i in range(5)],
            columns=[f"s_{j}" for j in range(6)],
        )
        data.iloc[0, :] = np.nan
        desc = pd.DataFrame(
            {
                "ID": data.columns.tolist(),
                "sample": list(range(1, 7)),
                "batch": [1, 1, 1, 2, 2, 2],
            }
        )
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=2)
        assert np.isnan(result.iloc[0]).all(), "All-NaN feature should stay NaN"
        assert not np.isnan(result.iloc[1:]).all(axis=None), "Other features should not be all NaN"

    def test_feature_missing_one_batch_entirely(self):
        """Feature missing one batch -> only adjustable across remaining batches."""
        data = pd.DataFrame(
            np.random.default_rng(3).normal(10, 1, size=(5, 9)),
            index=[f"p_{i}" for i in range(5)],
            columns=[f"s_{j}" for j in range(9)],
        )
        # Make feature 0 missing in batch 3
        data.iloc[0, 6:] = np.nan
        desc = pd.DataFrame(
            {
                "ID": data.columns.tolist(),
                "sample": list(range(1, 10)),
                "batch": [1, 1, 1, 2, 2, 2, 3, 3, 3],
            }
        )
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=2)
        # Feature 0 should have NaN in batch 3 columns
        assert np.isnan(result.iloc[0, 6:]).all()
        # Feature 0 should have values in batches 1-2
        assert not np.isnan(result.iloc[0, :6]).any()

    def test_duplicate_feature_names(self):
        """Duplicate feature indices should raise ValueError."""
        data = pd.DataFrame(
            np.random.default_rng(4).normal(10, 1, size=(4, 6)),
            index=["p_0", "p_0", "p_1", "p_2"],
            columns=[f"s_{j}" for j in range(6)],
        )
        desc = pd.DataFrame(
            {
                "ID": data.columns.tolist(),
                "sample": list(range(1, 7)),
                "batch": [1, 1, 1, 2, 2, 2],
            }
        )
        with pytest.raises(ValueError, match="duplicate feature names"):
            harmonize(data, desc, algorithm="ComBat", combat_mode=2)

    def test_dataframe_input(self):
        """Pipeline accepts DataFrames directly."""
        rng = np.random.default_rng(5)
        data = pd.DataFrame(
            rng.normal(10, 2, size=(10, 6)),
            index=[f"p_{i}" for i in range(10)],
            columns=[f"s_{j}" for j in range(6)],
        )
        data.iloc[:, 3:] += 3.0
        desc = pd.DataFrame(
            {
                "ID": data.columns.tolist(),
                "sample": list(range(1, 7)),
                "batch": [1, 1, 1, 2, 2, 2],
            }
        )
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=2)
        assert isinstance(result, pd.DataFrame)
        assert result.shape == data.shape

    def test_limma_through_pipeline(self):
        """limma algorithm works through the pipeline."""
        rng = np.random.default_rng(6)
        data = pd.DataFrame(
            rng.normal(10, 2, size=(15, 8)),
            index=[f"p_{i}" for i in range(15)],
            columns=[f"s_{j}" for j in range(8)],
        )
        data.iloc[:, 4:] += 3.0
        desc = pd.DataFrame(
            {
                "ID": data.columns.tolist(),
                "sample": list(range(1, 9)),
                "batch": [1, 1, 1, 1, 2, 2, 2, 2],
            }
        )
        result = harmonize(data, desc, algorithm="limma")
        assert isinstance(result, pd.DataFrame)
        assert not np.isnan(result).all(axis=None)

    def test_non_numeric_raises(self):
        """Data matrix with string column raises ValueError."""
        data = pd.DataFrame(
            {
                "s0": [1.0, 2.0, 3.0],
                "s1": ["a", "b", "c"],  # non-numeric
                "s2": [4.0, 5.0, 6.0],
                "s3": [7.0, 8.0, 9.0],
            },
            index=["p0", "p1", "p2"],
        )
        desc = pd.DataFrame(
            {
                "ID": ["s0", "s1", "s2", "s3"],
                "sample": [1, 2, 3, 4],
                "batch": [1, 1, 2, 2],
            }
        )
        with pytest.raises(ValueError, match="non-numeric columns"):
            harmonize(data, desc)

    def test_feature_only_one_batch_passthrough(self):
        """Feature present in only one batch returns values there, NaN elsewhere."""
        rng = np.random.default_rng(7)
        data = pd.DataFrame(
            rng.normal(10, 1, size=(5, 9)),
            index=[f"p_{i}" for i in range(5)],
            columns=[f"s_{j}" for j in range(9)],
        )
        # Feature 0: missing in batches 2 and 3 entirely
        data.iloc[0, 3:] = np.nan
        desc = pd.DataFrame(
            {
                "ID": data.columns.tolist(),
                "sample": list(range(1, 10)),
                "batch": [1, 1, 1, 2, 2, 2, 3, 3, 3],
            }
        )
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=2)
        # Feature 0 present only in batch 1 → single-batch passthrough → values unchanged
        np.testing.assert_array_equal(
            result.iloc[0, :3].values,
            data.iloc[0, :3].values,
            err_msg="Single-batch feature values should be unchanged",
        )
        # Batch 2 and 3 remain NaN
        assert np.isnan(result.iloc[0, 3:]).all()
        # Other features should be adjusted (not all-NaN)
        assert not np.isnan(result.iloc[1:]).any(axis=None)

    def test_all_features_missing_returns_all_nan(self):
        """All features entirely NaN → zero features pass spotting → all-NaN output, no crash."""
        data = pd.DataFrame(
            [[np.nan] * 4, [np.nan] * 4, [np.nan] * 4],
            index=["p0", "p1", "p2"],
            columns=["s0", "s1", "s2", "s3"],
        )
        desc = pd.DataFrame(
            {
                "ID": ["s0", "s1", "s2", "s3"],
                "sample": [1, 2, 3, 4],
                "batch": [1, 1, 2, 2],
            }
        )
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=1)
        assert result.shape == data.shape
        assert np.isnan(result.values).all(), "Expected all-NaN when all features are missing"

    def test_zero_features_pass_needed_values(self):
        """Feature with only 1 value per batch fails nv=2 → NaN passthrough."""
        # batch 1: one sample per feature; batch 2: one sample per feature → nv=2 fails all
        data = pd.DataFrame(
            {"s0": [1.0, 2.0, 3.0], "s1": [4.0, 5.0, 6.0]},
            index=["p0", "p1", "p2"],
        )
        desc = pd.DataFrame(
            {
                "ID": ["s0", "s1"],
                "sample": [1, 2],
                "batch": [1, 2],
            }
        )
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=1, needed_values=2)
        # Each batch has only 1 sample, so needed_values=2 is never met → all NaN
        assert result.shape == data.shape
        assert np.isnan(result.values).all(), "Expected all-NaN when no features meet needed_values"


# ===================================================================
# 7. Numerical stability and determinism
# ===================================================================


class TestNumericalStability:
    """Numerical properties: determinism, float32 promotion, memory isolation.

    Failure condition: output changes across identical runs, dtype
    promotion fails, or mutating the output affects the input.
    """
    def test_deterministic_combat(self):
        """Same input always gives same output."""
        rng = np.random.default_rng(50)
        data = rng.normal(10, 2, size=(30, 8))
        data[:, 4:] += 3.0
        batch = np.array([0, 0, 0, 0, 1, 1, 1, 1])

        result1 = combat(data, batch, par_prior=True, mean_only=False)
        result2 = combat(data, batch, par_prior=True, mean_only=False)
        np.testing.assert_array_equal(result1, result2, err_msg="ComBat not deterministic")

    def test_deterministic_limma(self):
        rng = np.random.default_rng(51)
        data = rng.normal(10, 2, size=(20, 6))
        data[:, 3:] += 2.0
        batch = np.array([0, 0, 0, 1, 1, 1])

        result1 = remove_batch_effect(data, batch)
        result2 = remove_batch_effect(data, batch)
        np.testing.assert_array_equal(result1, result2, err_msg="limma not deterministic")

    def test_combat_float32_input(self):
        """float32 input should be promoted to float64 without issues."""
        rng = np.random.default_rng(52)
        data = rng.normal(10, 2, size=(20, 6)).astype(np.float32)
        data[:, 3:] += 3.0
        batch = np.array([0, 0, 0, 1, 1, 1])
        result = combat(data, batch)
        assert result.dtype == np.float64
        assert not np.isnan(result).any()

    def test_limma_float32_input(self):
        rng = np.random.default_rng(53)
        data = rng.normal(10, 2, size=(20, 6)).astype(np.float32)
        data[:, 3:] += 2.0
        batch = np.array([0, 0, 0, 1, 1, 1])
        result = remove_batch_effect(data, batch)
        assert result.dtype == np.float64
        assert not np.isnan(result).any()

    def test_combat_output_not_alias(self):
        """Output must not share memory with input."""
        rng = np.random.default_rng(54)
        data = rng.normal(10, 2, size=(10, 6))
        data[:, 3:] += 2.0
        batch = np.array([0, 0, 0, 1, 1, 1])
        original = data.copy()
        result = combat(data, batch)
        # Mutating result should not affect original
        result[0, 0] = -9999.0
        np.testing.assert_array_equal(data, original)

    def test_limma_output_not_alias(self):
        rng = np.random.default_rng(55)
        data = rng.normal(10, 2, size=(10, 6))
        data[:, 3:] += 2.0
        batch = np.array([0, 0, 0, 1, 1, 1])
        original = data.copy()
        result = remove_batch_effect(data, batch)
        result[0, 0] = -9999.0
        np.testing.assert_array_equal(data, original)

    def test_combat_integer_data(self):
        """Integer input should be handled (promoted to float)."""
        data = np.array([[10, 12, 15, 18], [5, 7, 11, 14]], dtype=np.float64)
        batch = np.array([0, 0, 1, 1])
        result = combat(data, batch, par_prior=True, mean_only=True)
        assert result.dtype == np.float64
        assert not np.isnan(result).any()

    def test_combat_uniform_features(self):
        """Features constant within each batch should not blow up."""
        data = np.array(
            [
                [10.0, 10.0, 10.0, 20.0, 20.0, 20.0],
                [5.0, 5.0, 5.0, 15.0, 15.0, 15.0],
                [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
            ]
        )
        batch = np.array([0, 0, 0, 1, 1, 1])
        # mean_only=True should handle this (variance=0 clamped)
        result = combat(data, batch, par_prior=True, mean_only=True)
        assert not np.isnan(result).any()
        assert np.isfinite(result).all()


# ===================================================================
# 8. Spotting logic unit tests
# ===================================================================


class TestSpottingEdgeCases:
    """Edge cases for per-feature batch presence detection.

    Failure condition: an all-NaN feature, partial batch absence, or
    needed_values threshold produces an incorrect affiliation tuple.
    """
    def test_no_missing(self):
        """All data present → every feature sees all batches."""
        data = pd.DataFrame(np.ones((5, 6)))
        batch = np.array([1, 1, 1, 2, 2, 2])
        block = batch.copy()
        result = build_affiliation_list(data, batch, block, needed_values=2)
        assert all(affil == (1, 2) for affil in result)

    def test_one_batch_all_nan(self):
        """Feature entirely NaN in one batch → only other batch in affiliation."""
        data = pd.DataFrame(np.ones((3, 6)))
        data.iloc[0, 3:] = np.nan  # Feature 0: NaN in batch 2
        batch = np.array([1, 1, 1, 2, 2, 2])
        block = batch.copy()
        result = build_affiliation_list(data, batch, block, needed_values=2)
        assert result[0] == (1,)  # Only batch 1 eligible
        assert result[1] == (1, 2)
        assert result[2] == (1, 2)

    def test_feature_insufficient_in_all_batches(self):
        """Feature with < needed_values everywhere → empty affiliation."""
        data = pd.DataFrame(np.ones((3, 6)))
        data.iloc[0, :] = np.nan
        batch = np.array([1, 1, 1, 2, 2, 2])
        block = batch.copy()
        result = build_affiliation_list(data, batch, block, needed_values=2)
        assert result[0] == ()  # No batches qualify

    def test_needed_values_1(self):
        """needed_values=1: only need 1 non-NaN per batch."""
        data = pd.DataFrame(np.ones((3, 6)))
        data.iloc[0, 0:2] = np.nan  # Still 1 value in batch 1
        batch = np.array([1, 1, 1, 2, 2, 2])
        block = batch.copy()
        result = build_affiliation_list(data, batch, block, needed_values=1)
        assert result[0] == (1, 2)

    def test_needed_values_2_stricter(self):
        """needed_values=2 is stricter than 1."""
        data = pd.DataFrame(np.ones((3, 6)))
        data.iloc[0, 0:2] = np.nan  # Only 1 value in batch 1
        batch = np.array([1, 1, 1, 2, 2, 2])
        result_nv1 = build_affiliation_list(data, batch, batch, needed_values=1)
        result_nv2 = build_affiliation_list(data, batch, batch, needed_values=2)
        assert result_nv1[0] == (1, 2)  # 1 value in batch 1 suffices
        assert result_nv2[0] == (2,)  # Not enough in batch 1

    def test_three_batches_partial_missing(self):
        """Feature present in only 2 of 3 batches."""
        data = pd.DataFrame(np.ones((2, 9)))
        data.iloc[0, 6:] = np.nan  # Missing batch 3
        batch = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3])
        block = batch.copy()
        result = build_affiliation_list(data, batch, block, needed_values=2)
        assert result[0] == (1, 2)
        assert result[1] == (1, 2, 3)


# ===================================================================
# 9. Splitting integration
# ===================================================================


class TestSplittingRebuild:
    """Splitting produces correct sub-DataFrames and reassembles them.

    Failure condition: NaN placement is wrong, groups are split
    incorrectly, or the output does not match direct adjustment.
    """
    def test_no_missing_single_group(self):
        """Complete data → one sub-df, result matches direct combat."""
        rng = np.random.default_rng(60)
        data = pd.DataFrame(
            rng.normal(10, 2, size=(10, 6)),
            index=[f"p_{i}" for i in range(10)],
            columns=[f"s_{j}" for j in range(6)],
        )
        data.iloc[:, 3:] += 3.0
        batch = np.array([1, 1, 1, 2, 2, 2])
        block = batch.copy()
        affiliation = build_affiliation_list(data, batch, block, needed_values=2)

        sub_dfs = splitting(affiliation, data, batch, block, algorithm="ComBat", combat_mode=2)
        result = pd.concat(sub_dfs, axis=0)

        # Should match direct combat
        direct = adjust_combat(data, batch, mode=2)
        np.testing.assert_allclose(result.values, direct.values, atol=1e-12)

    def test_partial_missing_produces_nans(self):
        """Features missing a batch appear with NaN in that batch's columns."""
        rng = np.random.default_rng(61)
        data = pd.DataFrame(
            rng.normal(10, 2, size=(5, 9)),
            index=[f"p_{i}" for i in range(5)],
            columns=[f"s_{j}" for j in range(9)],
        )
        data.iloc[0, 6:] = np.nan  # Feature 0 missing batch 3
        batch = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3])
        block = batch.copy()
        affiliation = build_affiliation_list(data, batch, block, needed_values=2)

        sub_dfs = splitting(affiliation, data, batch, block, algorithm="ComBat", combat_mode=2)
        result = pd.concat(sub_dfs, axis=0)

        # Feature 0: NaN in batch 3 columns
        assert np.isnan(result.iloc[0, 6:]).all()
        # Feature 0: values in batches 1-2
        assert not np.isnan(result.iloc[0, :6]).any()

    def test_all_missing_feature_stays_nan(self):
        """Completely NaN feature → stays all NaN after splitting."""
        rng = np.random.default_rng(62)
        data = pd.DataFrame(
            rng.normal(10, 2, size=(5, 6)),
            index=[f"p_{i}" for i in range(5)],
            columns=[f"s_{j}" for j in range(6)],
        )
        data.iloc[0, :] = np.nan
        batch = np.array([1, 1, 1, 2, 2, 2])
        block = batch.copy()
        affiliation = build_affiliation_list(data, batch, block, needed_values=2)

        sub_dfs = splitting(affiliation, data, batch, block, algorithm="limma")
        result = pd.concat(sub_dfs, axis=0)
        assert np.isnan(result.iloc[0]).all()

    def test_limma_through_splitting(self):
        """limma adjustment works through full splitting pipeline."""
        rng = np.random.default_rng(63)
        data = pd.DataFrame(
            rng.normal(10, 2, size=(10, 6)),
            index=[f"p_{i}" for i in range(10)],
            columns=[f"s_{j}" for j in range(6)],
        )
        data.iloc[:, 3:] += 3.0
        batch = np.array([1, 1, 1, 2, 2, 2])
        block = batch.copy()
        affiliation = build_affiliation_list(data, batch, block, needed_values=2)

        sub_dfs = splitting(affiliation, data, batch, block, algorithm="limma")
        result = pd.concat(sub_dfs, axis=0)

        direct = adjust_limma(data, batch)
        np.testing.assert_allclose(result.values, direct.values, atol=1e-12)


# ===================================================================
# 10. Singleton batch (R forces mean_only)
# ===================================================================


@pytest.mark.skipif(
    not _fixture_exists("singleton_combat_mode2.tsv"),
    reason="Singleton fixtures not generated",
)
class TestSingletonBatch:
    """R forces mean_only=TRUE when a batch has 1 sample.

    Parametric modes (1,2) collapse to the same result; likewise
    nonparametric (3,4).  We keep only mode 2 and mode 4 fixtures.
    """

    @pytest.fixture(autouse=True)
    def _load(self):
        self.data = _load_tsv("singleton_input.tsv")
        self.batch = _load_batch("singleton_batch.csv")

    @pytest.mark.parametrize("mode", [2, 4])
    def test_mean_only_matches_r(self, mode):
        """Our mean_only modes should match R's singleton output."""
        expected = _load_tsv(f"singleton_combat_mode{mode}.tsv")
        params = _MODE_PARAMS[mode]
        result = combat(self.data, self.batch, **params)
        np.testing.assert_allclose(
            result,
            expected,
            rtol=1e-4,
            atol=1e-6,
            err_msg=f"Singleton mode {mode} mismatch",
        )


# ===================================================================
# 11. needed_values parameter (Step 3)
# ===================================================================


class TestNeededValuesParameter:
    """Step 3: verify needed_values threshold and auto-select logic.

        Helper datasets use unequal batch sizes so that changing the threshold
        genuinely includes or excludes specific batches:

    * ``_batch_data_9``: 9 samples, batches [4, 4, 1] (singleton batch 3)
    * ``_batch_data_10``: 10 samples, batches [4, 4, 2] (small batch 3)
        * ``_monotonic_data`` -  6 samples, batches [3, 2, 1] + structured absences
    """

    @staticmethod
    def _batch_data_9():
        """5 features x 9 samples; batches [4, 4, 1]; no NaN; batch effects applied."""
        rng = np.random.default_rng(40)
        data = pd.DataFrame(
            rng.normal(10, 1, size=(5, 9)),
            index=[f"p_{i}" for i in range(5)],
            columns=[f"s_{j}" for j in range(9)],
        )
        data.iloc[:, 4:8] += 2.0
        data.iloc[:, 8] += 4.0
        desc = pd.DataFrame(
            {
                "ID": data.columns.tolist(),
                "sample": list(range(1, 10)),
                "batch": [1] * 4 + [2] * 4 + [3] * 1,
            }
        )
        return data, desc

    @staticmethod
    def _batch_data_10():
        """5 features x 10 samples; batches [4, 4, 2]; no NaN; batch effects applied."""
        rng = np.random.default_rng(41)
        data = pd.DataFrame(
            rng.normal(10, 1, size=(5, 10)),
            index=[f"p_{i}" for i in range(5)],
            columns=[f"s_{j}" for j in range(10)],
        )
        data.iloc[:, 4:8] += 2.0
        data.iloc[:, 8:] += 4.0
        desc = pd.DataFrame(
            {
                "ID": data.columns.tolist(),
                "sample": list(range(1, 11)),
                "batch": [1] * 4 + [2] * 4 + [3] * 2,
            }
        )
        return data, desc

    @staticmethod
    def _monotonic_data():
        """6 features x 6 samples; batches [3, 2, 1]; structural absences.

        Absence pattern (whole-batch NaN):
          Features 0-1: present in all 3 batches
          Features 2-3: absent in batch 3 (1 sample)
          Features 4-5: absent in batches 2 and 3

        Expected NaN cells in output by needed_values:
          nv=1 →  8  (features 2-3 lose 1 col; features 4-5 lose 3 cols)
          nv=2 → 10  (features 0-3 lose 1 col; features 4-5 lose 3 cols)
          nv=3 → 18  (all 6 features passthrough, losing batches 2+3)
          nv=4 → 36  (all batches excluded, everything NaN)
        """
        rng = np.random.default_rng(42)
        data = pd.DataFrame(
            rng.normal(10, 1, size=(6, 6)),
            index=[f"p_{i}" for i in range(6)],
            columns=[f"s_{j}" for j in range(6)],
        )
        data.iloc[:, 3:5] += 2.0
        data.iloc[:, 5] += 4.0
        data.iloc[2:4, 5] = np.nan  # features 2-3 absent in batch 3
        data.iloc[4:, 3:] = np.nan  # features 4-5 absent in batches 2+3
        desc = pd.DataFrame(
            {
                "ID": data.columns.tolist(),
                "sample": list(range(1, 7)),
                "batch": [1, 1, 1, 2, 2, 3],
            }
        )
        return data, desc

    # ------------------------------------------------------------------
    # Explicit threshold tests
    # ------------------------------------------------------------------

    def test_nv1_includes_singleton_batch(self):
        """needed_values=1 includes a batch with only 1 sample."""
        data, desc = self._batch_data_9()
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=2, needed_values=1)
        assert not np.isnan(result.iloc[:, 8]).all(), (
            "Singleton batch column should be adjusted with needed_values=1"
        )

    def test_nv2_excludes_singleton_batch(self):
        """needed_values=2 excludes a batch that has only 1 sample."""
        data, desc = self._batch_data_9()
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=2, needed_values=2)
        assert np.isnan(result.iloc[:, 8]).all(), (
            "Singleton batch column should be NaN with needed_values=2"
        )

    def test_nv2_includes_two_sample_batch(self):
        """needed_values=2 includes a batch with exactly 2 samples."""
        data, desc = self._batch_data_10()
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=2, needed_values=2)
        assert not np.isnan(result.iloc[:, 8:]).any(axis=None), (
            "Two-sample batch columns should be adjusted with needed_values=2"
        )

    def test_nv3_excludes_two_sample_batch(self):
        """needed_values=3 excludes a batch with only 2 samples."""
        data, desc = self._batch_data_10()
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=2, needed_values=3)
        assert np.isnan(result.iloc[:, 8:]).all(axis=None), (
            "Two-sample batch columns should be NaN with needed_values=3"
        )

    # ------------------------------------------------------------------
    # Auto-select tests
    # ------------------------------------------------------------------

    def test_default_nv_mode1_is_2(self):
        """mode=1 auto-selects needed_values=2; produces the same NaN pattern."""
        data, desc = self._batch_data_9()
        result_auto = harmonize(data, desc, algorithm="ComBat", combat_mode=1, needed_values=None)
        result_two = harmonize(data, desc, algorithm="ComBat", combat_mode=1, needed_values=2)
        np.testing.assert_array_equal(
            np.isnan(result_auto.values),
            np.isnan(result_two.values),
            err_msg="NaN patterns must match: mode 1 auto vs explicit nv=2",
        )

    def test_default_nv_mode2_is_1(self):
        """mode=2 auto-selects needed_values=1; produces the same NaN pattern."""
        data, desc = self._batch_data_9()
        result_auto = harmonize(data, desc, algorithm="ComBat", combat_mode=2, needed_values=None)
        result_one = harmonize(data, desc, algorithm="ComBat", combat_mode=2, needed_values=1)
        np.testing.assert_array_equal(
            np.isnan(result_auto.values),
            np.isnan(result_one.values),
            err_msg="NaN patterns must match: mode 2 auto vs explicit nv=1",
        )

    def test_default_nv_limma_is_2(self):
        """limma auto-selects needed_values=2; produces the same NaN pattern."""
        data, desc = self._batch_data_9()
        result_auto = harmonize(data, desc, algorithm="limma", needed_values=None)
        result_two = harmonize(data, desc, algorithm="limma", needed_values=2)
        np.testing.assert_array_equal(
            np.isnan(result_auto.values),
            np.isnan(result_two.values),
            err_msg="NaN patterns must match: limma auto vs explicit nv=2",
        )

    def test_mode1_mode2_auto_select_differ(self):
        """Auto nv=2 (mode 1) vs auto nv=1 (mode 2) produce different NaN patterns."""
        data, desc = self._batch_data_9()
        result_mode1 = harmonize(data, desc, algorithm="ComBat", combat_mode=1)
        result_mode2 = harmonize(data, desc, algorithm="ComBat", combat_mode=2)
        # Mode 1 (auto nv=2) excludes singleton → NaN in last column
        assert np.isnan(result_mode1.iloc[:, 8]).all()
        # Mode 2 (auto nv=1) includes singleton → not all-NaN
        assert not np.isnan(result_mode2.iloc[:, 8]).all()

    # ------------------------------------------------------------------
    # Explicit overrides auto-select
    # ------------------------------------------------------------------

    def test_explicit_nv3_overrides_mode1_auto(self):
        """Explicit nv=3 with mode=1 excludes a batch that auto (nv=2) includes."""
        data, desc = self._batch_data_10()
        result_auto = harmonize(data, desc, algorithm="ComBat", combat_mode=1)
        result_nv3 = harmonize(data, desc, algorithm="ComBat", combat_mode=1, needed_values=3)
        # Auto (nv=2) includes 2-sample batch → no NaN in cols 8-9
        assert not np.isnan(result_auto.iloc[:, 8:]).any(axis=None)
        # Explicit nv=3 excludes 2-sample batch → cols 8-9 all NaN
        assert np.isnan(result_nv3.iloc[:, 8:]).all(axis=None)

    def test_explicit_nv1_overrides_mode2_auto(self):
        """Explicit nv=1 with mode=2 includes a batch that auto (nv=2, but wait: mode2 auto=1).

        Re-framed: mode=1 auto=2 excludes singleton; explicit nv=1 on same mode includes it.
        """
        data, desc = self._batch_data_9()
        # Mode=2 auto → nv=1 → includes singleton
        result_auto = harmonize(data, desc, algorithm="ComBat", combat_mode=2)
        assert not np.isnan(result_auto.iloc[:, 8]).all()
        # Mode=2 explicit nv=2 → excludes singleton
        result_nv2 = harmonize(data, desc, algorithm="ComBat", combat_mode=2, needed_values=2)
        assert np.isnan(result_nv2.iloc[:, 8]).all()

    # ------------------------------------------------------------------
    # Monotonicity: more features produce NaN as nv increases
    # ------------------------------------------------------------------

    def test_total_nan_increases_with_nv(self):
        """Total NaN cells in output increases weakly as needed_values increases."""
        data, desc = self._monotonic_data()
        nan_totals = []
        for nv in [1, 2, 3, 4]:
            result = harmonize(data, desc, algorithm="ComBat", combat_mode=2, needed_values=nv)
            nan_totals.append(int(np.isnan(result.values).sum()))
        for i in range(len(nan_totals) - 1):
            assert nan_totals[i] <= nan_totals[i + 1], (
                f"NaN count should be non-decreasing with nv; got {nan_totals}"
            )


# ===================================================================
# 12. NaN propagation audit (Step 4)
# ===================================================================


class TestNaNPropagation:
    """Step 4: verify the NaN firewall between the pipeline and adjusters.

    The core invariant: sub-dataframes handed to adjust_combat / adjust_limma
    must never contain NaN, even when the input data has structural
    (whole-batch) missing values.  Verified via monkeypatching.
    """

    @staticmethod
    def _structural_nan_data():
        """10 features x 9 samples; 3 batches of 3; structured whole-batch NaN.

        Feature 0: absent in batch 3. Feature 1: absent in batches 2+3.
        Features 2-9: fully present.
        """
        rng = np.random.default_rng(300)
        data = pd.DataFrame(
            rng.normal(10, 1, size=(10, 9)),
            index=[f"p_{i}" for i in range(10)],
            columns=[f"s_{j}" for j in range(9)],
        )
        data.iloc[:, 3:6] += 2.0
        data.iloc[:, 6:] += 4.0
        data.iloc[0, 6:] = np.nan  # feature 0 absent in batch 3
        data.iloc[1, 3:] = np.nan  # feature 1 absent in batches 2+3
        desc = pd.DataFrame(
            {
                "ID": data.columns.tolist(),
                "sample": list(range(1, 10)),
                "batch": [1] * 3 + [2] * 3 + [3] * 3,
            }
        )
        return data, desc

    # ------------------------------------------------------------------
    # Monkeypatch spy tests
    # ------------------------------------------------------------------

    def test_no_nan_reaches_combat(self, monkeypatch):
        """Sub-dataframes sent to combat must never contain NaN."""
        import harmonizepy.splitting as split_mod

        original = split_mod.combat
        nan_call_counts = []

        def spy(data, batch, *, par_prior=True, mean_only=False, ref_batch=None):
            if np.isnan(data).any():
                nan_call_counts.append(int(np.isnan(data).sum()))
            return original(data, batch, par_prior=par_prior, mean_only=mean_only, ref_batch=ref_batch)

        monkeypatch.setattr(split_mod, "combat", spy)

        data, desc = self._structural_nan_data()
        harmonize(data, desc, algorithm="ComBat", combat_mode=2)

        assert len(nan_call_counts) == 0, (
            f"combat received NaN in {len(nan_call_counts)} call(s): {nan_call_counts}"
        )

    def test_no_nan_reaches_limma(self, monkeypatch):
        """Sub-dataframes sent to remove_batch_effect must never contain NaN."""
        import harmonizepy.splitting as split_mod

        original = split_mod.remove_batch_effect
        nan_call_counts = []

        def spy(data, batch):
            if np.isnan(data).any():
                nan_call_counts.append(int(np.isnan(data).sum()))
            return original(data, batch)

        monkeypatch.setattr(split_mod, "remove_batch_effect", spy)

        data, desc = self._structural_nan_data()
        harmonize(data, desc, algorithm="limma")

        assert len(nan_call_counts) == 0, (
            f"remove_batch_effect received NaN in {len(nan_call_counts)} call(s): {nan_call_counts}"
        )

    # ------------------------------------------------------------------
    # Output NaN correctness
    # ------------------------------------------------------------------

    def test_combat_no_new_nan_on_clean_input(self):
        """All-numeric input to ComBat produces no NaN in output."""
        rng = np.random.default_rng(301)
        data = pd.DataFrame(
            rng.normal(10, 2, size=(20, 8)),
            index=[f"p_{i}" for i in range(20)],
            columns=[f"s_{j}" for j in range(8)],
        )
        data.iloc[:, 4:] += 3.0
        desc = pd.DataFrame(
            {
                "ID": data.columns.tolist(),
                "sample": list(range(1, 9)),
                "batch": [1] * 4 + [2] * 4,
            }
        )
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=2)
        assert not np.isnan(result.values).any(), "Clean input must produce no NaN in output"

    def test_limma_no_new_nan_on_clean_input(self):
        """All-numeric input to limma produces no NaN in output."""
        rng = np.random.default_rng(302)
        data = pd.DataFrame(
            rng.normal(10, 2, size=(20, 8)),
            index=[f"p_{i}" for i in range(20)],
            columns=[f"s_{j}" for j in range(8)],
        )
        data.iloc[:, 4:] += 3.0
        desc = pd.DataFrame(
            {
                "ID": data.columns.tolist(),
                "sample": list(range(1, 9)),
                "batch": [1] * 4 + [2] * 4,
            }
        )
        result = harmonize(data, desc, algorithm="limma")
        assert not np.isnan(result.values).any(), "Clean input must produce no NaN in output"

    def test_present_features_no_nan_despite_missing_neighbours(self):
        """Features fully present in all batches have no NaN in output, even when
        neighbouring features are structurally missing from some batches."""
        data, desc = self._structural_nan_data()
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=2)
        # Features 2-9 are fully present → their output rows must have no NaN
        assert not np.isnan(result.iloc[2:].values).any(), (
            "Fully-present features should have no NaN in output"
        )

    def test_output_nan_confined_to_absent_batch_columns(self):
        """For a structurally absent batch, NaN in output is confined to that batch's columns."""
        data, desc = self._structural_nan_data()
        result = harmonize(data, desc, algorithm="ComBat", combat_mode=2)
        # Feature 0 absent in batch 3 (cols 6-8) → NaN there, values elsewhere
        assert np.isnan(result.iloc[0, 6:]).all()
        assert not np.isnan(result.iloc[0, :6]).any()
        # Feature 1 absent in batches 2+3 (cols 3-8) → NaN there, values in batch 1 (cols 0-2)
        assert np.isnan(result.iloc[1, 3:]).all()
        assert not np.isnan(result.iloc[1, :3]).any()


# ============================================================================
# Blocking, sort+block, and unique-removal R concordance
# ============================================================================


def _concordance_check(result, expected, rtol, atol, label):
    """Shared NaN + allclose assertion for all Phase 2 concordance tests."""
    shared_idx = result.index.intersection(expected.index)
    shared_cols = result.columns.intersection(expected.columns)
    r = result.loc[shared_idx, shared_cols].values
    e = expected.loc[shared_idx, shared_cols].values
    nan_mask = np.isnan(e)
    assert np.isnan(r[nan_mask]).all(), f"{label}: missing NaN where R has NaN"
    assert not np.isnan(r[~nan_mask]).any(), f"{label}: extra NaN in Python output"
    valid = ~nan_mask
    if valid.any():
        np.testing.assert_allclose(r[valid], e[valid], rtol=rtol, atol=atol, err_msg=label)


@pytest.mark.skipif(
    not _fixture_exists("medium_block2_combat_mode1.tsv"),
    reason="Blocking R fixtures not generated (run generate_blocking_fixtures.R)",
)
class TestBlockingRConcordance:
    """Full pipeline with blocking (no sort) vs R HarmonizR.

    Datasets:
    - medium:  100 features x 12 samples x 3 batches, 30% structural missing
    - highmiss: 50 features x 9 samples x 3 batches, ~65% missing
    - large:   500 features x 30 samples x 5 batches, no missing
    """

    @pytest.fixture(autouse=True)
    def _load(self):
        self.med_data = _load_tsv_df("medium_input.tsv")
        self.med_desc = pd.read_csv(FIXTURE_DIR / "medium_batch.csv")
        self.hm_data = _load_tsv_df("highmiss_input.tsv")
        self.hm_desc = pd.read_csv(FIXTURE_DIR / "highmiss_batch.csv")
        self.lg_data = _load_tsv_df("large_input.tsv")
        self.lg_desc = pd.read_csv(FIXTURE_DIR / "large_batch.csv")

    @pytest.mark.parametrize("mode", [1, 2, 3, 4])
    def test_medium_block2_combat(self, mode):
        expected = _load_tsv_df(f"medium_block2_combat_mode{mode}.tsv")
        result = harmonize(
            self.med_data,
            self.med_desc,
            algorithm="ComBat",
            combat_mode=mode,
            block=2,
        )
        rtol = 5e-4 if mode in (1, 3) else 1e-5
        _concordance_check(
            result, expected, rtol=rtol, atol=1e-4, label=f"medium block=2 ComBat mode {mode}"
        )

    def test_medium_block2_limma(self):
        expected = _load_tsv_df("medium_block2_limma.tsv")
        result = harmonize(self.med_data, self.med_desc, algorithm="limma", block=2)
        _concordance_check(result, expected, rtol=1e-8, atol=1e-8, label="medium block=2 limma")

    @pytest.mark.parametrize("mode", [1, 2, 3, 4])
    def test_highmiss_block2_combat(self, mode):
        expected = _load_tsv_df(f"highmiss_block2_combat_mode{mode}.tsv")
        result = harmonize(
            self.hm_data,
            self.hm_desc,
            algorithm="ComBat",
            combat_mode=mode,
            block=2,
        )
        rtol = 5e-4 if mode in (1, 3) else 1e-5
        _concordance_check(
            result, expected, rtol=rtol, atol=1e-4, label=f"highmiss block=2 ComBat mode {mode}"
        )

    def test_highmiss_block2_limma(self):
        expected = _load_tsv_df("highmiss_block2_limma.tsv")
        result = harmonize(self.hm_data, self.hm_desc, algorithm="limma", block=2)
        _concordance_check(result, expected, rtol=1e-8, atol=1e-8, label="highmiss block=2 limma")

    def test_large_block4_combat_mode1(self):
        expected = _load_tsv_df("large_block4_combat_mode1.tsv")
        result = harmonize(
            self.lg_data,
            self.lg_desc,
            algorithm="ComBat",
            combat_mode=1,
            block=4,
        )
        _concordance_check(
            result, expected, rtol=5e-4, atol=1e-4, label="large block=4 ComBat mode 1"
        )


@pytest.mark.skipif(
    not _fixture_exists("medium_sparsity_block2_combat_mode1.tsv"),
    reason="Sort+block R fixtures not generated (run generate_blocking_fixtures.R)",
)
class TestSortBlockRConcordance:
    """Full pipeline with sort + blocking vs R HarmonizR.

    Covers the three Python sort strategies (sparsity, jaccard, seriation)
    mapped to R's "sparsity_sort", "jaccard_sort", "seriation_sort" strings.
    """

    @pytest.fixture(autouse=True)
    def _load(self):
        self.med_data = _load_tsv_df("medium_input.tsv")
        self.med_desc = pd.read_csv(FIXTURE_DIR / "medium_batch.csv")
        self.hm_data = _load_tsv_df("highmiss_input.tsv")
        self.hm_desc = pd.read_csv(FIXTURE_DIR / "highmiss_batch.csv")
        self.lg_data = _load_tsv_df("large_input.tsv")
        self.lg_desc = pd.read_csv(FIXTURE_DIR / "large_batch.csv")

    @pytest.mark.parametrize("mode", [1, 2, 3, 4])
    def test_medium_sparsity_block2_combat(self, mode):
        expected = _load_tsv_df(f"medium_sparsity_block2_combat_mode{mode}.tsv")
        result = harmonize(
            self.med_data,
            self.med_desc,
            algorithm="ComBat",
            combat_mode=mode,
            sort="sparsity",
            block=2,
        )
        rtol = 5e-4 if mode in (1, 3) else 1e-5
        _concordance_check(
            result,
            expected,
            rtol=rtol,
            atol=1e-4,
            label=f"medium sparsity block=2 ComBat mode {mode}",
        )

    def test_medium_sparsity_block2_limma(self):
        expected = _load_tsv_df("medium_sparsity_block2_limma.tsv")
        result = harmonize(
            self.med_data,
            self.med_desc,
            algorithm="limma",
            sort="sparsity",
            block=2,
        )
        _concordance_check(
            result, expected, rtol=1e-8, atol=1e-8, label="medium sparsity block=2 limma"
        )

    def test_medium_jaccard_block2_combat_mode1(self):
        expected = _load_tsv_df("medium_jaccard_block2_combat_mode1.tsv")
        result = harmonize(
            self.med_data,
            self.med_desc,
            algorithm="ComBat",
            combat_mode=1,
            sort="jaccard",
            block=2,
        )
        _concordance_check(
            result, expected, rtol=5e-4, atol=1e-4, label="medium jaccard block=2 ComBat mode 1"
        )

    def test_medium_seriation_block2_combat_mode1(self):
        expected = _load_tsv_df("medium_seriation_block2_combat_mode1.tsv")
        result = harmonize(
            self.med_data,
            self.med_desc,
            algorithm="ComBat",
            combat_mode=1,
            sort="seriation",
            block=2,
        )
        _concordance_check(
            result, expected, rtol=5e-4, atol=1e-4, label="medium seriation block=2 ComBat mode 1"
        )

    def test_large_sparsity_block4_combat_mode1(self):
        expected = _load_tsv_df("large_sparsity_block4_combat_mode1.tsv")
        result = harmonize(
            self.lg_data,
            self.lg_desc,
            algorithm="ComBat",
            combat_mode=1,
            sort="sparsity",
            block=4,
        )
        _concordance_check(
            result, expected, rtol=5e-4, atol=1e-4, label="large sparsity block=4 ComBat mode 1"
        )

    def test_highmiss_sparsity_block2_combat_mode1(self):
        expected = _load_tsv_df("highmiss_sparsity_block2_combat_mode1.tsv")
        result = harmonize(
            self.hm_data,
            self.hm_desc,
            algorithm="ComBat",
            combat_mode=1,
            sort="sparsity",
            block=2,
        )
        _concordance_check(
            result, expected, rtol=5e-4, atol=1e-4, label="highmiss sparsity block=2 ComBat mode 1"
        )


@pytest.mark.skipif(
    not _fixture_exists("highmiss_nour_combat_mode1.tsv"),
    reason="Unique-removal R fixture not generated (run generate_blocking_fixtures.R)",
)
class TestUniqueRemovalRConcordance:
    """unique_removal toggle vs R HarmonizR (ur= parameter) on high-missingness data.

    The highmiss dataset (50 features, 3 batches, ~65% missing) has enough
    features per batch-combination that no combo is a singleton.  Therefore
    ur=True and ur=False produce the same feature set and values for this
    dataset.  The tests verify:
      1. Python ur=True matches R ur=TRUE (values).
      2. Python ur=False matches R ur=FALSE (values).
      3. Python ur=True retains >= features than ur=False.
      4. Feature counts match R for both settings.
    """

    @pytest.fixture(autouse=True)
    def _load(self):
        self.hm_data = _load_tsv_df("highmiss_input.tsv")
        self.hm_desc = pd.read_csv(FIXTURE_DIR / "highmiss_batch.csv")

    def test_ur_true_matches_r(self):
        """ur=True (default) matches R ur=TRUE fixture."""
        expected = _load_tsv_df("highmiss_harmonizr_combat_mode1.tsv")
        result = harmonize(
            self.hm_data,
            self.hm_desc,
            algorithm="ComBat",
            combat_mode=1,
            unique_removal=True,
        )
        _concordance_check(
            result, expected, rtol=5e-4, atol=1e-4, label="highmiss ur=True ComBat mode 1"
        )

    def test_ur_false_matches_r(self):
        """ur=False matches R ur=FALSE fixture (feature count and values)."""
        expected = _load_tsv_df("highmiss_nour_combat_mode1.tsv")
        result = harmonize(
            self.hm_data,
            self.hm_desc,
            algorithm="ComBat",
            combat_mode=1,
            unique_removal=False,
        )
        assert len(result) == len(expected), (
            f"Feature count: Python={len(result)}, R={len(expected)}"
        )
        _concordance_check(
            result, expected, rtol=5e-4, atol=1e-4, label="highmiss ur=False ComBat mode 1"
        )

    def test_ur_true_retains_at_least_as_many_features_as_ur_false(self):
        """ur=True retains >= features than ur=False."""
        result_ur = harmonize(
            self.hm_data, self.hm_desc, algorithm="ComBat", combat_mode=1, unique_removal=True
        )
        result_nour = harmonize(
            self.hm_data, self.hm_desc, algorithm="ComBat", combat_mode=1, unique_removal=False
        )
        assert len(result_ur) >= len(result_nour), (
            f"ur=True:{len(result_ur)} < ur=False:{len(result_nour)}"
        )

    def test_ur_true_feature_count_equals_r(self):
        """ur=True feature count matches R ur=TRUE."""
        expected = _load_tsv_df("highmiss_harmonizr_combat_mode1.tsv")
        result = harmonize(
            self.hm_data, self.hm_desc, algorithm="ComBat", combat_mode=1, unique_removal=True
        )
        assert len(result) == len(expected), (
            f"Python ur=True: {len(result)}, R ur=True: {len(expected)}"
        )

    def test_ur_false_feature_count_equals_r(self):
        """ur=False feature count matches R ur=FALSE."""
        expected = _load_tsv_df("highmiss_nour_combat_mode1.tsv")
        result = harmonize(
            self.hm_data, self.hm_desc, algorithm="ComBat", combat_mode=1, unique_removal=False
        )
        assert len(result) == len(expected), (
            f"Python ur=False: {len(result)}, R ur=False: {len(expected)}"
        )
